// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ClockSinkDomain_8(	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [8:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [28:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [8:0]  auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        out_woready_5;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _impl_in_fifo_full;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:82:24]
  wire        _impl_out_fifo_empty;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:82:24]
  wire        _impl_o_done;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:82:24]
  wire        _impl_tag_valid;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:82:24]
  wire [31:0] _impl_out_fifo_data;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:82:24]
  reg         rst;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:67:34]
  reg         input_finish;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:71:34]
  reg  [31:0] data_in;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:72:30]
  wire        in_bits_read = auto_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
  wire        _out_T_3 = auto_in_a_bits_address[11:4] == 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24]
  wire        start = out_woready_5 & auto_in_a_bits_mask[0] & auto_in_a_bits_data[0];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:69:35, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        write_en = out_woready_5 & auto_in_a_bits_mask[0] & auto_in_a_bits_data[1];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:68:35, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        read_en = out_woready_5 & auto_in_a_bits_mask[0] & auto_in_a_bits_data[2];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:70:35, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_5 = auto_in_a_valid & auto_in_d_ready & ~in_bits_read & ~(auto_in_a_bits_address[3]) & _out_T_3;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :87:24]
  always @(posedge auto_clock_in_clock) begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
    if (auto_clock_in_reset) begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
      rst <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9, :67:34]
      input_finish <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9, :71:34]
    end
    else begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
      if (out_woready_5 & auto_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        rst <= auto_in_a_bits_data[4];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:67:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_5 & auto_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        input_finish <= auto_in_a_bits_data[3];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:71:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    end
    if (out_woready_5 & (&{{8{auto_in_a_bits_mask[7]}}, {8{auto_in_a_bits_mask[6]}}, {8{auto_in_a_bits_mask[5]}}, {8{auto_in_a_bits_mask[4]}}}))	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      data_in <= auto_in_a_bits_data[63:32];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:72:30, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
    initial begin	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
        end	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
        rst = _RANDOM[1'h0][0];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9, :67:34]
        input_finish = _RANDOM[1'h0][1];	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9, :67:34, :71:34]
        data_in = {_RANDOM[1'h0][31:2], _RANDOM[1'h1][1:0]};	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9, :67:34, :72:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ascon impl (	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:82:24]
    .i_clk          (auto_clock_in_clock),
    .i_rst          (auto_clock_in_reset | rst),	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:67:34, :87:47]
    .i_write_data   (write_en),	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:68:35, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .i_start        (start),	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:69:35, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .out_fifo_rd_en (read_en),	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:70:35, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .input_finish   (input_finish),	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:71:34]
    .i_data         (data_in),	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:72:30]
    .in_fifo_full   (_impl_in_fifo_full),
    .out_fifo_empty (_impl_out_fifo_empty),
    .o_done         (_impl_o_done),
    .tag_valid      (_impl_tag_valid),
    .out_fifo_data  (_impl_out_fifo_data)
  );	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:82:24]
  assign auto_in_a_ready = auto_in_d_ready;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
  assign auto_in_d_valid = auto_in_a_valid;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
  assign auto_in_d_bits_opcode = {2'h0, in_bits_read};	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :105:19]
  assign auto_in_d_bits_size = auto_in_a_bits_size;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
  assign auto_in_d_bits_source = auto_in_a_bits_source;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9]
  assign auto_in_d_bits_data = _out_T_3 ? (auto_in_a_bits_address[3] ? {28'h0, _impl_o_done, _impl_tag_valid, _impl_out_fifo_empty, _impl_in_fifo_full, _impl_out_fifo_data} : {data_in, 27'h0, rst, input_finish, read_en, write_en, start}) : 64'h0;	// @[generators/chipyard/src/main/scala/cipher/ascon.scala:64:9, :67:34, :68:35, :69:35, :70:35, :71:34, :72:30, :82:24, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:{10,48}]
endmodule

