// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ClockSinkDomain_11(	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [8:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [28:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [8:0]  auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        out_woready_6;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _impl_io_oValid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:149:30]
  wire [31:0] _impl_io_oRand;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:149:30]
  reg         rst;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:140:33]
  reg         enable;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:141:33]
  reg         next;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:142:33]
  reg  [31:0] delay;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:143:33]
  wire        in_bits_read = auto_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
  wire        _out_T_3 = auto_in_a_bits_address[11:4] == 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24]
  wire        _out_wofireMux_T_2 = auto_in_a_valid & auto_in_d_ready & ~in_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :87:24]
  wire        out_woready_3 = _out_wofireMux_T_2 & ~(auto_in_a_bits_address[3]) & _out_T_3;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_6 = _out_wofireMux_T_2 & auto_in_a_bits_address[3] & _out_T_3;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  always @(posedge auto_clock_in_clock) begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
    if (auto_clock_in_reset) begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
      rst <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :140:33]
      enable <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :141:33]
      next <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :142:33]
      delay <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:143:33]
    end
    else begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
      if (out_woready_3 & auto_in_a_bits_mask[1])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        rst <= auto_in_a_bits_data[8];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:140:33, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_3 & auto_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        enable <= auto_in_a_bits_data[0];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:141:33, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_3 & auto_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        next <= auto_in_a_bits_data[1];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:142:33, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      if (out_woready_6 & (&{{8{auto_in_a_bits_mask[3]}}, {8{auto_in_a_bits_mask[2]}}, {8{auto_in_a_bits_mask[1]}}, {8{auto_in_a_bits_mask[0]}}}))	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        delay <= auto_in_a_bits_data[31:0];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:143:33, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
    initial begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
        end	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
        rst = _RANDOM[1'h0][0];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :140:33]
        enable = _RANDOM[1'h0][1];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :140:33, :141:33]
        next = _RANDOM[1'h0][2];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :140:33, :142:33]
        delay = {_RANDOM[1'h0][31:3], _RANDOM[1'h1][2:0]};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :140:33, :143:33]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TRNGMMIOModule impl (	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:149:30]
    .clock     (auto_clock_in_clock),
    .reset     (auto_clock_in_reset),
    .io_iRst   (auto_clock_in_reset | rst),	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:140:33, :152:44]
    .io_iEn    (enable),	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:141:33]
    .io_iDelay (delay),	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:143:33]
    .io_iNext  (next),	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:142:33]
    .io_oValid (_impl_io_oValid),
    .io_oRand  (_impl_io_oRand)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:149:30]
  assign auto_in_a_ready = auto_in_d_ready;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
  assign auto_in_d_valid = auto_in_a_valid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
  assign auto_in_d_bits_opcode = {2'h0, in_bits_read};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :105:19]
  assign auto_in_d_bits_size = auto_in_a_bits_size;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
  assign auto_in_d_bits_source = auto_in_a_bits_source;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11]
  assign auto_in_d_bits_data = _out_T_3 ? (auto_in_a_bits_address[3] ? {out_woready_6 & (&{{8{auto_in_a_bits_mask[7]}}, {8{auto_in_a_bits_mask[6]}}, {8{auto_in_a_bits_mask[5]}}, {8{auto_in_a_bits_mask[4]}}}) ? auto_in_a_bits_data[63:32] : _impl_io_oRand, delay} : {31'h0, _impl_io_oValid, 23'h0, rst, 6'h0, next, enable}) : 64'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:137:11, :140:33, :141:33, :142:33, :143:33, :149:30, :158:18, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:74:{88,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:{10,48}]
endmodule

