// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module EgressUnit_1(	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
  input         clock,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
  input         reset,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
  input         io_in_0_valid,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input         io_in_0_bits_head,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input         io_in_0_bits_tail,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input  [72:0] io_in_0_bits_payload,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input  [2:0]  io_in_0_bits_flow_ingress_node,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input  [1:0]  io_in_0_bits_flow_ingress_node_id,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  output        io_credit_available_0,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  output        io_channel_status_0_occupied,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input         io_allocs_0_alloc,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input         io_credit_alloc_0_alloc,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input         io_credit_alloc_0_tail,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  input         io_out_ready,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  output        io_out_valid,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  output        io_out_bits_head,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  output        io_out_bits_tail,	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
  output [72:0] io_out_bits_payload	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:18:14]
);

  wire       _q_io_enq_ready;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:22:17]
  wire [1:0] _q_io_count;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:22:17]
  reg        channel_empty;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:20:30]
  wire       _q_io_enq_bits_ingress_id_T_4 = io_in_0_bits_flow_ingress_node_id == 2'h1;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:32:27]
  `ifndef SYNTHESIS	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:38:9]
    always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:38:9]
      if (~reset & io_in_0_valid & ~_q_io_enq_ready) begin	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:22:17, :38:{9,27,30}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:38:9]
          $error("Assertion failed\n    at EgressUnit.scala:38 assert(!(q.io.enq.valid && !q.io.enq.ready))\n");	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:38:9]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:38:9]
          $fatal;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:38:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
    if (reset)	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
      channel_empty <= 1'h1;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7, :20:30]
    else	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
      channel_empty <= ~io_allocs_0_alloc & (io_credit_alloc_0_alloc & io_credit_alloc_0_tail | channel_empty);	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:20:30, :44:{34,62}, :45:19, :49:29, :50:19]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
    initial begin	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
        `INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
        channel_empty = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7, :20:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue3_EgressFlit q (	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:22:17]
    .clock                  (clock),
    .reset                  (reset),
    .io_enq_ready           (_q_io_enq_ready),
    .io_enq_valid           (io_in_0_valid),
    .io_enq_bits_head       (io_in_0_bits_head),
    .io_enq_bits_tail       (io_in_0_bits_tail),
    .io_enq_bits_payload    (io_in_0_bits_payload),
    .io_enq_bits_ingress_id ((io_in_0_bits_flow_ingress_node == 3'h4 & _q_io_enq_bits_ingress_id_T_4 ? 4'hD : 4'h0) | {4{io_in_0_bits_flow_ingress_node == 3'h5 & _q_io_enq_bits_ingress_id_T_4}}),	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:31:{39,75}, :32:27, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_deq_ready           (io_out_ready),
    .io_deq_valid           (io_out_valid),
    .io_deq_bits_head       (io_out_bits_head),
    .io_deq_bits_tail       (io_out_bits_tail),
    .io_deq_bits_payload    (io_out_bits_payload),
    .io_count               (_q_io_count)
  );	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:22:17]
  assign io_credit_available_0 = _q_io_count == 2'h0;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7, :22:17, :40:40]
  assign io_channel_status_0_occupied = ~channel_empty;	// @[generators/constellation/src/main/scala/router/EgressUnit.scala:12:7, :20:30, :41:36]
endmodule

