./AnalogToUInt_1.v
./GenericDigitalInIOCell.v
./GenericDigitalOutIOCell.v
./PowerOnResetFPGAOnly.v
./UIntToAnalog_1.v
./aes.v
./aes_core.v
./aes_decipher_block.v
./aes_encipher_block.v
./aes_inv_sbox.v
./aes_key_mem.v
./aes_sbox.v
./ascon.v
./ascon_core.v
./asconp.v
./asic_nand.v
./asic_not.v
./chacha.v
./chacha_core.v
./chacha_qr.v
./ecdsa_block_v1.preprocessed.sv
./f_permutation.v
./fifo.v
./keccak.v
./keccak_wrapper.v
./padder.v
./padder1.v
./plusarg_reader.v
./poly1305.preprocessed.v
./rconst.v
./round.v
