// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module InputBuffer_9(	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
  input         clock,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
  input         reset,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
  input         io_enq_0_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input         io_enq_0_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input         io_enq_0_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input  [72:0] io_enq_0_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input  [3:0]  io_enq_0_bits_virt_channel_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_0_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_0_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_0_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_1_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_1_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_1_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_2_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_2_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_2_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input         io_deq_3_ready,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_3_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_3_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_3_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_3_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_4_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_4_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_4_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_5_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_5_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_5_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_6_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_6_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_6_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input         io_deq_7_ready,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_7_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_7_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_7_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_7_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input         io_deq_8_ready,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_8_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_8_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_8_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_8_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  input         io_deq_9_ready,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_9_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_9_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output        io_deq_9_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
  output [72:0] io_deq_9_bits_payload	// @[generators/constellation/src/main/scala/router/InputUnit.scala:51:14]
);

  wire             _qs_9_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_8_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_7_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_6_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_5_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_4_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_3_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_2_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_1_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire             _qs_0_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  wire [74:0]      _mem_ext_R0_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R1_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R2_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R3_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R4_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R5_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R6_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R7_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R8_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  wire [74:0]      _mem_ext_R9_data;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  reg  [3:0]       heads_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_3;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_6;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_7;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       heads_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
  reg  [3:0]       tails_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_3;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_6;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_7;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  reg  [3:0]       tails_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
  wire             _tails_T_30 = io_enq_0_bits_virt_channel_id == 4'h0;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_31 = io_enq_0_bits_virt_channel_id == 4'h1;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_32 = io_enq_0_bits_virt_channel_id == 4'h2;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_33 = io_enq_0_bits_virt_channel_id == 4'h3;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_34 = io_enq_0_bits_virt_channel_id == 4'h4;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_35 = io_enq_0_bits_virt_channel_id == 4'h5;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_36 = io_enq_0_bits_virt_channel_id == 4'h6;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_37 = io_enq_0_bits_virt_channel_id == 4'h7;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_38 = io_enq_0_bits_virt_channel_id == 4'h8;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             _tails_T_39 = io_enq_0_bits_virt_channel_id == 4'h9;	// @[src/main/scala/chisel3/util/Mux.scala:32:36]
  wire             direct_to_q = (_tails_T_30 & _qs_0_io_enq_ready | _tails_T_31 & _qs_1_io_enq_ready | _tails_T_32 & _qs_2_io_enq_ready | _tails_T_33 & _qs_3_io_enq_ready | _tails_T_34 & _qs_4_io_enq_ready | _tails_T_35 & _qs_5_io_enq_ready | _tails_T_36 & _qs_6_io_enq_ready | _tails_T_37 & _qs_7_io_enq_ready | _tails_T_38 & _qs_8_io_enq_ready | _tails_T_39 & _qs_9_io_enq_ready) & (_tails_T_30 & heads_0 == tails_0 | _tails_T_31 & heads_1 == tails_1 | _tails_T_32 & heads_2 == tails_2 | _tails_T_33 & heads_3 == tails_3 | _tails_T_34 & heads_4 == tails_4 | _tails_T_35 & heads_5 == tails_5 | _tails_T_36 & heads_6 == tails_6 | _tails_T_37 & heads_7 == tails_7 | _tails_T_38 & heads_8 == tails_8 | _tails_T_39 & heads_9 == tails_9);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :96:62, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  wire             mem_MPORT_en = io_enq_0_valid & ~direct_to_q;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:96:62, :100:{27,30}]
  wire [15:0][3:0] _GEN = {{tails_0}, {tails_0}, {tails_0}, {tails_0}, {tails_0}, {tails_0}, {tails_9}, {tails_8}, {tails_7}, {tails_6}, {tails_5}, {tails_4}, {tails_3}, {tails_2}, {tails_1}, {tails_0}};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :102:16]
  wire             _GEN_0 = io_enq_0_bits_virt_channel_id == 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_1 = io_enq_0_bits_virt_channel_id == 4'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_2 = io_enq_0_bits_virt_channel_id == 4'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_3 = io_enq_0_bits_virt_channel_id == 4'h3;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_4 = io_enq_0_bits_virt_channel_id == 4'h4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_5 = io_enq_0_bits_virt_channel_id == 4'h5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_6 = io_enq_0_bits_virt_channel_id == 4'h6;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_7 = io_enq_0_bits_virt_channel_id == 4'h7;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_8 = io_enq_0_bits_virt_channel_id == 4'h8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_9 = io_enq_0_bits_virt_channel_id == 4'h9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:103:45]
  wire             _GEN_10 = io_enq_0_valid & direct_to_q;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:96:62, :107:34]
  wire             can_to_q_0 = heads_0 != tails_0 & _qs_0_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_1 = heads_1 != tails_1 & _qs_1_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_2 = heads_2 != tails_2 & _qs_2_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_3 = heads_3 != tails_3 & _qs_3_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_4 = heads_4 != tails_4 & _qs_4_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_5 = heads_5 != tails_5 & _qs_5_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_6 = heads_6 != tails_6 & _qs_6_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_7 = heads_7 != tails_7 & _qs_7_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_8 = heads_8 != tails_8 & _qs_8_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire             can_to_q_9 = heads_9 != tails_9 & _qs_9_io_enq_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :87:24, :88:49, :90:49, :117:{60,70}]
  wire [9:0]       to_q_oh_enc = can_to_q_0 ? 10'h1 : can_to_q_1 ? 10'h2 : can_to_q_2 ? 10'h4 : can_to_q_3 ? 10'h8 : can_to_q_4 ? 10'h10 : can_to_q_5 ? 10'h20 : can_to_q_6 ? 10'h40 : can_to_q_7 ? 10'h80 : can_to_q_8 ? 10'h100 : {can_to_q_9, 9'h0};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:117:70, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire             _GEN_11 = can_to_q_0 | can_to_q_1 | can_to_q_2 | can_to_q_3 | can_to_q_4 | can_to_q_5 | can_to_q_6 | can_to_q_7 | can_to_q_8 | can_to_q_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:117:70, generators/rocket-chip/src/main/scala/util/package.scala:81:59]
  wire [3:0]       head = (to_q_oh_enc[0] ? heads_0 : 4'h0) | (to_q_oh_enc[1] ? heads_1 : 4'h0) | (to_q_oh_enc[2] ? heads_2 : 4'h0) | (to_q_oh_enc[3] ? heads_3 : 4'h0) | (to_q_oh_enc[4] ? heads_4 : 4'h0) | (to_q_oh_enc[5] ? heads_5 : 4'h0) | (to_q_oh_enc[6] ? heads_6 : 4'h0) | (to_q_oh_enc[7] ? heads_7 : 4'h0) | (to_q_oh_enc[8] ? heads_8 : 4'h0) | (to_q_oh_enc[9] ? heads_9 : 4'h0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_12 = _GEN_11 & to_q_oh_enc[0];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_13 = _GEN_11 & to_q_oh_enc[1];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_14 = _GEN_11 & to_q_oh_enc[2];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_15 = _GEN_11 & to_q_oh_enc[3];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_16 = _GEN_11 & to_q_oh_enc[4];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_17 = _GEN_11 & to_q_oh_enc[5];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_18 = _GEN_11 & to_q_oh_enc[6];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_19 = _GEN_11 & to_q_oh_enc[7];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_20 = _GEN_11 & to_q_oh_enc[8];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire             _GEN_21 = _GEN_11 & to_q_oh_enc[9];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:44, :120:27, :127:29, :128:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  wire [3:0]       _tails_T_61 = _GEN[io_enq_0_bits_virt_channel_id] == ({1'h0, {1'h0, {2{_tails_T_33}}} | {3{_tails_T_37}}} | (_tails_T_38 ? 4'hB : 4'h0) | {4{_tails_T_39}}) ? {_tails_T_38, _tails_T_37, 2'h0} | (_tails_T_39 ? 4'hC : 4'h0) : _GEN[io_enq_0_bits_virt_channel_id] + 4'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :102:16, :103:51, :104:14, :106:14, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  wire [6:0]       _to_q_T_2 = {6'h0, to_q_oh_enc[9]} | to_q_oh_enc[7:1];	// @[src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:31:18, :32:28]
  wire [2:0]       _to_q_T_4 = _to_q_T_2[6:4] | _to_q_T_2[2:0];	// @[src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:28]
  wire             _to_q_T_6 = _to_q_T_4[2] | _to_q_T_4[0];	// @[src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:28]
  wire [3:0]       to_q = {|(to_q_oh_enc[9:8]), |(_to_q_T_2[6:3]), |(_to_q_T_4[2:1]), _to_q_T_6};	// @[src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:30:18, :32:{10,14,28}]
  wire [3:0]       _heads_T_41 = head == ({1'h0, {1'h0, {2{to_q_oh_enc[3]}}} | {3{to_q_oh_enc[7]}}} | (to_q_oh_enc[8] ? 4'hB : 4'h0) | {4{to_q_oh_enc[9]}}) ? {to_q_oh_enc[8:7], 2'h0} | (to_q_oh_enc[9] ? 4'hC : 4'h0) : head + 4'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :122:27, :123:16, :125:16, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
  always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
    if (reset) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
      heads_0 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_1 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_2 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_3 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_4 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_5 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_6 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_7 <= 4'h4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_8 <= 4'h8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      heads_9 <= 4'hC;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24]
      tails_0 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_1 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_2 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_3 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_4 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_5 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_6 <= 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_7 <= 4'h4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_8 <= 4'h8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
      tails_9 <= 4'hC;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24]
    end
    else begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
      if (_GEN_11 & {to_q_oh_enc[9:8], |(_to_q_T_2[6:3]), |(_to_q_T_4[2:1]), _to_q_T_6} == 5'h0)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:30:18, :32:{10,14,28}]
        heads_0 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h1)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_1 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h2)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_2 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h3)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_3 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h4)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_4 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h5)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_5 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h6)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_6 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h7)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_7 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h8)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_8 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (_GEN_11 & to_q == 4'h9)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :120:27, :122:21, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/OneHot.scala:32:10]
        heads_9 <= _heads_T_41;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:86:24, :122:27]
      if (mem_MPORT_en & _GEN_0)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_0 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_1)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_1 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_2)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_2 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_3)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_3 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_4)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_4 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_5)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_5 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_6)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_6 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_7)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_7 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_8)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_8 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
      if (mem_MPORT_en & _GEN_9)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :100:{27,44}, :103:45]
        tails_9 <= _tails_T_61;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:87:24, :103:51]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
    initial begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
        `INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
        end	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
        heads_0 = _RANDOM[2'h0][3:0];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_1 = _RANDOM[2'h0][7:4];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_2 = _RANDOM[2'h0][11:8];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_3 = _RANDOM[2'h0][15:12];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_4 = _RANDOM[2'h0][19:16];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_5 = _RANDOM[2'h0][23:20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_6 = _RANDOM[2'h0][27:24];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_7 = _RANDOM[2'h0][31:28];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_8 = _RANDOM[2'h1][3:0];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        heads_9 = _RANDOM[2'h1][7:4];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24]
        tails_0 = _RANDOM[2'h1][11:8];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24, :87:24]
        tails_1 = _RANDOM[2'h1][15:12];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24, :87:24]
        tails_2 = _RANDOM[2'h1][19:16];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24, :87:24]
        tails_3 = _RANDOM[2'h1][23:20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24, :87:24]
        tails_4 = _RANDOM[2'h1][27:24];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24, :87:24]
        tails_5 = _RANDOM[2'h1][31:28];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :86:24, :87:24]
        tails_6 = _RANDOM[2'h2][3:0];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :87:24]
        tails_7 = _RANDOM[2'h2][7:4];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :87:24]
        tails_8 = _RANDOM[2'h2][11:8];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :87:24]
        tails_9 = _RANDOM[2'h2][15:12];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7, :87:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:49:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  mem_16x75 mem_ext (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
    .R0_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R0_en   (_GEN_11 & to_q_oh_enc[9]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .R1_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R1_en   (_GEN_11 & to_q_oh_enc[8]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R1_clk  (clock),
    .R1_data (_mem_ext_R1_data),
    .R2_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R2_en   (_GEN_11 & to_q_oh_enc[7]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R2_clk  (clock),
    .R2_data (_mem_ext_R2_data),
    .R3_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R3_en   (_GEN_11 & to_q_oh_enc[6]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R3_clk  (clock),
    .R3_data (_mem_ext_R3_data),
    .R4_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R4_en   (_GEN_11 & to_q_oh_enc[5]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R4_clk  (clock),
    .R4_data (_mem_ext_R4_data),
    .R5_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R5_en   (_GEN_11 & to_q_oh_enc[4]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R5_clk  (clock),
    .R5_data (_mem_ext_R5_data),
    .R6_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R6_en   (_GEN_11 & to_q_oh_enc[3]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R6_clk  (clock),
    .R6_data (_mem_ext_R6_data),
    .R7_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R7_en   (_GEN_11 & to_q_oh_enc[2]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R7_clk  (clock),
    .R7_data (_mem_ext_R7_data),
    .R8_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R8_en   (_GEN_11 & to_q_oh_enc[1]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R8_clk  (clock),
    .R8_data (_mem_ext_R8_data),
    .R9_addr (head),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .R9_en   (_GEN_11 & to_q_oh_enc[0]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :120:27, :127:29, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    .R9_clk  (clock),
    .R9_data (_mem_ext_R9_data),
    .W0_addr (_GEN[io_enq_0_bits_virt_channel_id]),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:102:16]
    .W0_en   (mem_MPORT_en),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:100:27]
    .W0_clk  (clock),
    .W0_data ({io_enq_0_bits_payload, io_enq_0_bits_tail, io_enq_0_bits_head})	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18]
  Queue1_BaseFlit qs_0 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_0_io_enq_ready),
    .io_enq_valid        (_GEN_12 | ~mem_MPORT_en & _GEN_10 & _GEN_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_12 ? _mem_ext_R9_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_12 ? _mem_ext_R9_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_12 ? _mem_ext_R9_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (1'h0),
    .io_deq_valid        (/* unused */),
    .io_deq_bits_head    (io_deq_0_bits_head),
    .io_deq_bits_tail    (io_deq_0_bits_tail),
    .io_deq_bits_payload (io_deq_0_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_1 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_1_io_enq_ready),
    .io_enq_valid        (_GEN_13 | ~mem_MPORT_en & _GEN_10 & _GEN_1),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_13 ? _mem_ext_R8_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_13 ? _mem_ext_R8_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_13 ? _mem_ext_R8_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (1'h0),
    .io_deq_valid        (/* unused */),
    .io_deq_bits_head    (io_deq_1_bits_head),
    .io_deq_bits_tail    (io_deq_1_bits_tail),
    .io_deq_bits_payload (io_deq_1_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_2 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_2_io_enq_ready),
    .io_enq_valid        (_GEN_14 | ~mem_MPORT_en & _GEN_10 & _GEN_2),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_14 ? _mem_ext_R7_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_14 ? _mem_ext_R7_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_14 ? _mem_ext_R7_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (1'h0),
    .io_deq_valid        (/* unused */),
    .io_deq_bits_head    (io_deq_2_bits_head),
    .io_deq_bits_tail    (io_deq_2_bits_tail),
    .io_deq_bits_payload (io_deq_2_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_3 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_3_io_enq_ready),
    .io_enq_valid        (_GEN_15 | ~mem_MPORT_en & _GEN_10 & _GEN_3),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_15 ? _mem_ext_R6_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_15 ? _mem_ext_R6_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_15 ? _mem_ext_R6_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (io_deq_3_ready),
    .io_deq_valid        (io_deq_3_valid),
    .io_deq_bits_head    (io_deq_3_bits_head),
    .io_deq_bits_tail    (io_deq_3_bits_tail),
    .io_deq_bits_payload (io_deq_3_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_4 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_4_io_enq_ready),
    .io_enq_valid        (_GEN_16 | ~mem_MPORT_en & _GEN_10 & _GEN_4),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_16 ? _mem_ext_R5_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_16 ? _mem_ext_R5_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_16 ? _mem_ext_R5_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (1'h0),
    .io_deq_valid        (/* unused */),
    .io_deq_bits_head    (io_deq_4_bits_head),
    .io_deq_bits_tail    (io_deq_4_bits_tail),
    .io_deq_bits_payload (io_deq_4_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_5 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_5_io_enq_ready),
    .io_enq_valid        (_GEN_17 | ~mem_MPORT_en & _GEN_10 & _GEN_5),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_17 ? _mem_ext_R4_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_17 ? _mem_ext_R4_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_17 ? _mem_ext_R4_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (1'h0),
    .io_deq_valid        (/* unused */),
    .io_deq_bits_head    (io_deq_5_bits_head),
    .io_deq_bits_tail    (io_deq_5_bits_tail),
    .io_deq_bits_payload (io_deq_5_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_6 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_6_io_enq_ready),
    .io_enq_valid        (_GEN_18 | ~mem_MPORT_en & _GEN_10 & _GEN_6),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_18 ? _mem_ext_R3_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_18 ? _mem_ext_R3_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_18 ? _mem_ext_R3_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (1'h0),
    .io_deq_valid        (/* unused */),
    .io_deq_bits_head    (io_deq_6_bits_head),
    .io_deq_bits_tail    (io_deq_6_bits_tail),
    .io_deq_bits_payload (io_deq_6_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_7 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_7_io_enq_ready),
    .io_enq_valid        (_GEN_19 | ~mem_MPORT_en & _GEN_10 & _GEN_7),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_19 ? _mem_ext_R2_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_19 ? _mem_ext_R2_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_19 ? _mem_ext_R2_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (io_deq_7_ready),
    .io_deq_valid        (io_deq_7_valid),
    .io_deq_bits_head    (io_deq_7_bits_head),
    .io_deq_bits_tail    (io_deq_7_bits_tail),
    .io_deq_bits_payload (io_deq_7_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_8 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_8_io_enq_ready),
    .io_enq_valid        (_GEN_20 | ~mem_MPORT_en & _GEN_10 & _GEN_8),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_20 ? _mem_ext_R1_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_20 ? _mem_ext_R1_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_20 ? _mem_ext_R1_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (io_deq_8_ready),
    .io_deq_valid        (io_deq_8_valid),
    .io_deq_bits_head    (io_deq_8_bits_head),
    .io_deq_bits_tail    (io_deq_8_bits_tail),
    .io_deq_bits_payload (io_deq_8_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
  Queue1_BaseFlit qs_9 (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_qs_9_io_enq_ready),
    .io_enq_valid        (_GEN_21 | ~mem_MPORT_en & _GEN_10 & _GEN_9),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:91:31, :100:{27,44}, :103:45, :107:{34,50}, :109:55, :120:27, :127:29, :128:32]
    .io_enq_bits_head    (_GEN_21 ? _mem_ext_R0_data[0] : io_enq_0_bits_head),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_tail    (_GEN_21 ? _mem_ext_R0_data[1] : io_enq_0_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_enq_bits_payload (_GEN_21 ? _mem_ext_R0_data[74:2] : io_enq_0_bits_payload),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:85:18, :100:44, :120:27, :127:29, :128:32, :129:31]
    .io_deq_ready        (io_deq_9_ready),
    .io_deq_valid        (io_deq_9_valid),
    .io_deq_bits_head    (io_deq_9_bits_head),
    .io_deq_bits_tail    (io_deq_9_bits_tail),
    .io_deq_bits_payload (io_deq_9_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:90:49]
endmodule

