// Generated by CIRCT firtool-1.75.0
module IntSyncAsyncCrossingSink_n1x1(	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:74:9]
  input  clock,	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:74:9]
  output auto_out_0	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  SynchronizerShiftReg_w1_d3 chain (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_q  (auto_out_0)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
endmodule

