// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module OutputUnit_2(	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  input         clock,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  input         reset,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  input         io_in_0_valid,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_in_0_bits_head,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_in_0_bits_tail,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [72:0] io_in_0_bits_payload,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [2:0]  io_in_0_bits_flow_vnet_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [2:0]  io_in_0_bits_flow_ingress_node,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [1:0]  io_in_0_bits_flow_ingress_node_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [2:0]  io_in_0_bits_flow_egress_node,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [1:0]  io_in_0_bits_flow_egress_node_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [3:0]  io_in_0_bits_virt_channel_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_credit_available_1,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_credit_available_5,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_credit_available_9,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_channel_status_1_occupied,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_channel_status_5_occupied,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_channel_status_9_occupied,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_allocs_1_alloc,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_allocs_5_alloc,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_allocs_9_alloc,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_credit_alloc_1_alloc,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_credit_alloc_5_alloc,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input         io_credit_alloc_9_alloc,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_out_flit_0_valid,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_out_flit_0_bits_head,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output        io_out_flit_0_bits_tail,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output [72:0] io_out_flit_0_bits_payload,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output [2:0]  io_out_flit_0_bits_flow_vnet_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output [2:0]  io_out_flit_0_bits_flow_ingress_node,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output [1:0]  io_out_flit_0_bits_flow_ingress_node_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output [2:0]  io_out_flit_0_bits_flow_egress_node,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output [1:0]  io_out_flit_0_bits_flow_egress_node_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  output [3:0]  io_out_flit_0_bits_virt_channel_id,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [9:0]  io_out_credit_return,	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
  input  [9:0]  io_out_vc_free	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:58:14]
);

  reg       states_9_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
  reg [2:0] states_9_c;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
  reg       states_5_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
  reg [2:0] states_5_c;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
  reg       states_1_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
  reg [2:0] states_1_c;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
  `ifndef SYNTHESIS	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
    always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
      if (io_out_vc_free[1] & ~reset & ~states_1_occupied) begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :74:25, :75:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
          $error("Assertion failed\n    at OutputUnit.scala:75 assert(s.occupied)\n");	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
          $fatal;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
      end
      if (io_out_vc_free[5] & ~reset & ~states_5_occupied) begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :74:25, :75:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
          $error("Assertion failed\n    at OutputUnit.scala:75 assert(s.occupied)\n");	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
          $fatal;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
      end
      if (io_out_vc_free[9] & ~reset & ~states_9_occupied) begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :74:25, :75:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
          $error("Assertion failed\n    at OutputUnit.scala:75 assert(s.occupied)\n");	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
          $fatal;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:75:13]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
    if (reset) begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
      states_9_occupied <= 1'h0;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
      states_9_c <= 3'h4;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
      states_5_occupied <= 1'h0;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
      states_5_c <= 3'h4;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
      states_1_occupied <= 1'h0;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19]
      states_1_c <= 3'h4;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
    end
    else begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
      states_9_occupied <= io_allocs_9_alloc | ~(io_out_vc_free[9]) & states_9_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :74:{25,30}, :76:18, :82:20, :83:18]
      states_9_c <= states_9_c + {2'h0, io_out_credit_return[9]} - {2'h0, io_credit_alloc_9_alloc};	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :93:36, :96:{18,26}]
      states_5_occupied <= io_allocs_5_alloc | ~(io_out_vc_free[5]) & states_5_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :74:{25,30}, :76:18, :82:20, :83:18]
      states_5_c <= states_5_c + {2'h0, io_out_credit_return[5]} - {2'h0, io_credit_alloc_5_alloc};	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :93:36, :96:{18,26}]
      states_1_occupied <= io_allocs_1_alloc | ~(io_out_vc_free[1]) & states_1_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :74:{25,30}, :76:18, :82:20, :83:18]
      states_1_c <= states_1_c + {2'h0, io_out_credit_return[1]} - {2'h0, io_credit_alloc_1_alloc};	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:66:19, :93:36, :96:{18,26}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
    initial begin	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
        `INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
        end	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
        states_9_occupied = _RANDOM[3'h0][0];	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
        states_9_c = _RANDOM[3'h0][3:1];	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
        states_5_occupied = _RANDOM[3'h2][4];	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
        states_5_c = _RANDOM[3'h2][7:5];	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
        states_1_occupied = _RANDOM[3'h4][8];	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
        states_1_c = _RANDOM[3'h4][11:9];	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_credit_available_1 = |states_1_c;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19, :89:14]
  assign io_credit_available_5 = |states_5_c;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19, :89:14]
  assign io_credit_available_9 = |states_9_c;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19, :89:14]
  assign io_channel_status_1_occupied = states_1_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
  assign io_channel_status_5_occupied = states_5_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
  assign io_channel_status_9_occupied = states_9_occupied;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7, :66:19]
  assign io_out_flit_0_valid = io_in_0_valid;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_head = io_in_0_bits_head;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_tail = io_in_0_bits_tail;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_payload = io_in_0_bits_payload;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_flow_vnet_id = io_in_0_bits_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_flow_ingress_node = io_in_0_bits_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_flow_ingress_node_id = io_in_0_bits_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_flow_egress_node = io_in_0_bits_flow_egress_node;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_flow_egress_node_id = io_in_0_bits_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
  assign io_out_flit_0_bits_virt_channel_id = io_in_0_bits_virt_channel_id;	// @[generators/constellation/src/main/scala/router/OutputUnit.scala:52:7]
endmodule

