// Generated by CIRCT firtool-1.75.0
module RingOscillator(	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:39:7]
  input        io_i_en,	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:40:14]
  output [4:0] io_o_out	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:40:14]
);

  wire _asic_nand_0_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
  wire _inv_modules_asic_not_3_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  wire _inv_modules_asic_not_2_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  wire _inv_modules_asic_not_1_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  wire _inv_modules_asic_not_0_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_0 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_asic_nand_0_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
    .y (_inv_modules_asic_not_0_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_1 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_inv_modules_asic_not_0_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_inv_modules_asic_not_1_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_2 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_inv_modules_asic_not_1_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_inv_modules_asic_not_2_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_3 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_inv_modules_asic_not_2_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_inv_modules_asic_not_3_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_nand asic_nand_0 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
    .a (io_i_en),
    .b (_inv_modules_asic_not_3_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_asic_nand_0_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
  assign io_o_out = {_inv_modules_asic_not_3_y, _inv_modules_asic_not_2_y, _inv_modules_asic_not_1_y, _inv_modules_asic_not_0_y, _asic_nand_0_y};	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:39:7, :85:21, :90:29, :112:19]
endmodule

