// Generated by CIRCT firtool-1.75.0
module SynchronizerShiftReg_w8_d3(	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:169:7]
  input        clock,	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:169:7]
  input  [7:0] io_d,	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:36:14]
  output [7:0] io_q	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:36:14]
);

  wire _output_chain_7_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _output_chain_6_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _output_chain_5_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _output_chain_4_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _output_chain_3_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _output_chain_2_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _output_chain_1_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _output_chain_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[0]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain_1 (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[1]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_1_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain_2 (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[2]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_2_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain_3 (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[3]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_3_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain_4 (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[4]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_4_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain_5 (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[5]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_5_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain_6 (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[6]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_6_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  NonSyncResetSynchronizerPrimitiveShiftReg_d3 output_chain_7 (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  (io_d[7]),	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:173:39]
    .io_q  (_output_chain_7_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  assign io_q = {_output_chain_7_io_q, _output_chain_6_io_q, _output_chain_5_io_q, _output_chain_4_io_q, _output_chain_3_io_q, _output_chain_2_io_q, _output_chain_1_io_q, _output_chain_io_q};	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23, generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:169:7, :175:14]
endmodule

