// Generated by CIRCT firtool-1.75.0
module TLSlaveToNoC(	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:125:7]
  input         clock,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:125:7]
  input         reset,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:125:7]
  input         io_tilelink_a_ready,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_tilelink_a_valid,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [2:0]  io_tilelink_a_bits_opcode,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [2:0]  io_tilelink_a_bits_param,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [3:0]  io_tilelink_a_bits_size,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [3:0]  io_tilelink_a_bits_source,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [31:0] io_tilelink_a_bits_address,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [7:0]  io_tilelink_a_bits_mask,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [63:0] io_tilelink_a_bits_data,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_tilelink_a_bits_corrupt,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_tilelink_d_ready,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_tilelink_d_valid,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input  [2:0]  io_tilelink_d_bits_opcode,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input  [1:0]  io_tilelink_d_bits_param,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input  [3:0]  io_tilelink_d_bits_size,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input  [3:0]  io_tilelink_d_bits_source,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input  [1:0]  io_tilelink_d_bits_sink,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_tilelink_d_bits_denied,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input  [63:0] io_tilelink_d_bits_data,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_tilelink_d_bits_corrupt,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_flits_a_ready,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_a_valid,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_a_bits_head,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_a_bits_tail,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input  [72:0] io_flits_a_bits_payload,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_flits_b_valid,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_flits_c_ready,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_c_valid,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_c_bits_head,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_c_bits_tail,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_d_ready,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_flits_d_valid,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_flits_d_bits_head,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_flits_d_bits_tail,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [72:0] io_flits_d_bits_payload,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output [2:0]  io_flits_d_bits_egress_id,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  output        io_flits_e_ready,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_e_valid,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_e_bits_head,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
  input         io_flits_e_bits_tail	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:132:14]
);

  wire [64:0] _d_io_flit_bits_payload;	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:146:17]
  TLAFromNoC a (	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:143:17]
    .clock                    (clock),
    .reset                    (reset),
    .io_protocol_ready        (io_tilelink_a_ready),
    .io_protocol_valid        (io_tilelink_a_valid),
    .io_protocol_bits_opcode  (io_tilelink_a_bits_opcode),
    .io_protocol_bits_param   (io_tilelink_a_bits_param),
    .io_protocol_bits_size    (io_tilelink_a_bits_size),
    .io_protocol_bits_source  (io_tilelink_a_bits_source),
    .io_protocol_bits_address (io_tilelink_a_bits_address),
    .io_protocol_bits_mask    (io_tilelink_a_bits_mask),
    .io_protocol_bits_data    (io_tilelink_a_bits_data),
    .io_protocol_bits_corrupt (io_tilelink_a_bits_corrupt),
    .io_flit_ready            (io_flits_a_ready),
    .io_flit_valid            (io_flits_a_valid),
    .io_flit_bits_head        (io_flits_a_bits_head),
    .io_flit_bits_tail        (io_flits_a_bits_tail),
    .io_flit_bits_payload     (io_flits_a_bits_payload)
  );	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:143:17]
  TLBToNoC b (	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:144:17]
    .clock         (clock),
    .reset         (reset),
    .io_flit_valid (io_flits_b_valid)
  );	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:144:17]
  TLCFromNoC c (	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:145:17]
    .clock             (clock),
    .reset             (reset),
    .io_flit_ready     (io_flits_c_ready),
    .io_flit_valid     (io_flits_c_valid),
    .io_flit_bits_head (io_flits_c_bits_head),
    .io_flit_bits_tail (io_flits_c_bits_tail)
  );	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:145:17]
  TLDToNoC d (	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:146:17]
    .clock                    (clock),
    .reset                    (reset),
    .io_protocol_ready        (io_tilelink_d_ready),
    .io_protocol_valid        (io_tilelink_d_valid),
    .io_protocol_bits_opcode  (io_tilelink_d_bits_opcode),
    .io_protocol_bits_param   (io_tilelink_d_bits_param),
    .io_protocol_bits_size    (io_tilelink_d_bits_size),
    .io_protocol_bits_source  (io_tilelink_d_bits_source),
    .io_protocol_bits_sink    (io_tilelink_d_bits_sink),
    .io_protocol_bits_denied  (io_tilelink_d_bits_denied),
    .io_protocol_bits_data    (io_tilelink_d_bits_data),
    .io_protocol_bits_corrupt (io_tilelink_d_bits_corrupt),
    .io_flit_ready            (io_flits_d_ready),
    .io_flit_valid            (io_flits_d_valid),
    .io_flit_bits_head        (io_flits_d_bits_head),
    .io_flit_bits_tail        (io_flits_d_bits_tail),
    .io_flit_bits_payload     (_d_io_flit_bits_payload),
    .io_flit_bits_egress_id   (io_flits_d_bits_egress_id)
  );	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:146:17]
  TLEFromNoC e (	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:147:17]
    .clock             (clock),
    .reset             (reset),
    .io_flit_ready     (io_flits_e_ready),
    .io_flit_valid     (io_flits_e_valid),
    .io_flit_bits_head (io_flits_e_bits_head),
    .io_flit_bits_tail (io_flits_e_bits_tail)
  );	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:147:17]
  assign io_flits_d_bits_payload = {8'h0, _d_io_flit_bits_payload};	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:125:7, :146:17, :157:14]
endmodule

