// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TRNGMMIOModule(	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
  input         clock,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
  input         reset,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
  input         io_iRst,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  input         io_iEn,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  input  [31:0] io_iDelay,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  input         io_iNext,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  output        io_oValid,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  output [31:0] io_oRand	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
);

  wire [4:0]  _ro_io_o_out;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
  wire        _rg_io_o_bit;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20]
  reg         tick;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23]
  reg  [31:0] delayCnt;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27]
  reg  [31:0] shiftReg;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:93:27]
  reg  [4:0]  collectCnt;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29]
  reg         valid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:95:24]
  reg         nextTrigger_REG;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:98:44]
  wire        _GEN = io_iEn & ~tick;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23, :80:{17,20}]
  wire        _GEN_0 = io_iRst | io_iNext & ~nextTrigger_REG;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:98:{33,36,44}, :101:18]
  wire        _GEN_1 = tick & ~valid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23, :95:24, :106:{15,18}]
  always @(posedge clock) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    if (reset) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      tick <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23]
      delayCnt <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27]
      shiftReg <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:93:27]
      collectCnt <= 5'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29]
      valid <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:95:24]
    end
    else begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      tick <= ~io_iRst & (_GEN & delayCnt == io_iDelay | tick);	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23, :74:27, :76:18, :78:10, :80:{17,27}, :82:{23,38}, :83:14, :85:14, :89:14]
      if (io_iRst)	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
        delayCnt <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27]
      else if (_GEN)	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:80:17]
        delayCnt <= delayCnt + 32'h1;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27, :81:30]
      if (_GEN_0) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:101:18]
        shiftReg <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:93:27]
        collectCnt <= 5'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29]
      end
      else if (_GEN_1) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:106:15]
        shiftReg <= {shiftReg[30:0], _rg_io_o_bit};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20, :93:27, :107:{30,38}]
        collectCnt <= collectCnt + 5'h1;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29, :108:34]
      end
      valid <= ~_GEN_0 & (_GEN_1 & (&collectCnt) | valid);	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29, :95:24, :101:{18,33}, :103:11, :106:{15,26}, :109:{25,35}, :110:15, :112:15]
    end
    nextTrigger_REG <= io_iNext;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:98:44]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    initial begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        end	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        tick = _RANDOM[2'h0][0];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :73:23]
        delayCnt = {_RANDOM[2'h0][31:1], _RANDOM[2'h1][0]};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :73:23, :74:27]
        shiftReg = {_RANDOM[2'h1][31:1], _RANDOM[2'h2][0]};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :74:27, :93:27]
        collectCnt = _RANDOM[2'h2][5:1];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :94:29]
        valid = _RANDOM[2'h2][6];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :95:24]
        nextTrigger_REG = _RANDOM[2'h2][8];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :98:44]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RingGenerator rg (	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20]
    .clock       (clock),
    .reset       (reset),
    .io_i_rst    (io_iRst),
    .io_i_inject (_ro_io_o_out),	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
    .io_o_bit    (_rg_io_o_bit)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20]
  RingOscillator ro (	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
    .io_i_en  (io_iEn),
    .io_o_out (_ro_io_o_out)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
  assign io_oValid = valid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :95:24]
  assign io_oRand = valid ? shiftReg : 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :95:24, :119:20]
endmodule

