// Generated by CIRCT firtool-1.75.0
module ClockSinkDomain_1(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  output        auto_i2c_0_int_xing_out_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_i2c_0_control_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_i2c_0_control_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_i2c_0_control_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_i2c_0_control_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [8:0]  auto_i2c_0_control_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [30:0] auto_i2c_0_control_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_i2c_0_control_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_i2c_0_control_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_i2c_0_control_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_i2c_0_control_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_i2c_0_control_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_i2c_0_control_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [8:0]  auto_i2c_0_control_xing_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_i2c_0_control_xing_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_i2c_0_io_out_scl_in,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_i2c_0_io_out_scl_oe,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_i2c_0_io_out_sda_in,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_i2c_0_io_out_sda_oe,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  TLI2C i2c_0 (	// @[generators/rocket-chip-blocks/src/main/scala/devices/i2c/I2C.scala:597:49]
    .clock                               (auto_clock_in_clock),
    .reset                               (auto_clock_in_reset),
    .auto_int_xing_out_sync_0            (auto_i2c_0_int_xing_out_sync_0),
    .auto_control_xing_in_a_ready        (auto_i2c_0_control_xing_in_a_ready),
    .auto_control_xing_in_a_valid        (auto_i2c_0_control_xing_in_a_valid),
    .auto_control_xing_in_a_bits_opcode  (auto_i2c_0_control_xing_in_a_bits_opcode),
    .auto_control_xing_in_a_bits_size    (auto_i2c_0_control_xing_in_a_bits_size),
    .auto_control_xing_in_a_bits_source  (auto_i2c_0_control_xing_in_a_bits_source),
    .auto_control_xing_in_a_bits_address (auto_i2c_0_control_xing_in_a_bits_address),
    .auto_control_xing_in_a_bits_mask    (auto_i2c_0_control_xing_in_a_bits_mask),
    .auto_control_xing_in_a_bits_data    (auto_i2c_0_control_xing_in_a_bits_data),
    .auto_control_xing_in_d_ready        (auto_i2c_0_control_xing_in_d_ready),
    .auto_control_xing_in_d_valid        (auto_i2c_0_control_xing_in_d_valid),
    .auto_control_xing_in_d_bits_opcode  (auto_i2c_0_control_xing_in_d_bits_opcode),
    .auto_control_xing_in_d_bits_size    (auto_i2c_0_control_xing_in_d_bits_size),
    .auto_control_xing_in_d_bits_source  (auto_i2c_0_control_xing_in_d_bits_source),
    .auto_control_xing_in_d_bits_data    (auto_i2c_0_control_xing_in_d_bits_data),
    .auto_io_out_scl_in                  (auto_i2c_0_io_out_scl_in),
    .auto_io_out_scl_oe                  (auto_i2c_0_io_out_scl_oe),
    .auto_io_out_sda_in                  (auto_i2c_0_io_out_sda_in),
    .auto_io_out_sda_oe                  (auto_i2c_0_io_out_sda_oe)
  );	// @[generators/rocket-chip-blocks/src/main/scala/devices/i2c/I2C.scala:597:49]
endmodule

