// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module InputUnit_6(	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
  input         clock,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
  input         reset,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
  output [3:0]  io_router_req_bits_src_virt_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [2:0]  io_router_req_bits_flow_vnet_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [2:0]  io_router_req_bits_flow_ingress_node,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [1:0]  io_router_req_bits_flow_ingress_node_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [2:0]  io_router_req_bits_flow_egress_node,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [1:0]  io_router_req_bits_flow_egress_node_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_router_resp_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_router_resp_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_router_resp_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_router_resp_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_router_resp_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_router_resp_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_req_ready,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_vcalloc_req_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_vcalloc_resp_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_3_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_2_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_1_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_1_1,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_1_4,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_1_5,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_1_8,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_1_9,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_0_2,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_0_3,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_0_6,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_out_credit_available_0_7,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_salloc_req_0_ready,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_2,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_3,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_6,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_7,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_0_1,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_0_2,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_0_3,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_0_5,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_0_6,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_0_7,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_vc_sel_0_9,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_salloc_req_0_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_out_0_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_out_0_bits_flit_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output        io_out_0_bits_flit_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [72:0] io_out_0_bits_flit_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [2:0]  io_out_0_bits_flit_flow_vnet_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [2:0]  io_out_0_bits_flit_flow_ingress_node,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [1:0]  io_out_0_bits_flit_flow_ingress_node_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [2:0]  io_out_0_bits_flit_flow_egress_node,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [1:0]  io_out_0_bits_flit_flow_egress_node_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [3:0]  io_out_0_bits_out_virt_channel,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [3:0]  io_debug_va_stall,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [3:0]  io_debug_sa_stall,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_in_flit_0_valid,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_in_flit_0_bits_head,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input         io_in_flit_0_bits_tail,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input  [72:0] io_in_flit_0_bits_payload,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input  [2:0]  io_in_flit_0_bits_flow_vnet_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input  [2:0]  io_in_flit_0_bits_flow_ingress_node,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input  [1:0]  io_in_flit_0_bits_flow_ingress_node_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input  [2:0]  io_in_flit_0_bits_flow_egress_node,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input  [1:0]  io_in_flit_0_bits_flow_egress_node_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  input  [3:0]  io_in_flit_0_bits_virt_channel_id,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [9:0]  io_in_credit_return,	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
  output [9:0]  io_in_vc_free	// @[generators/constellation/src/main/scala/router/InputUnit.scala:170:14]
);

  wire        vcalloc_vals_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:266:32]
  wire        vcalloc_vals_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:266:32]
  wire        vcalloc_vals_5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:266:32]
  wire        vcalloc_vals_1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:266:32]
  wire        _salloc_arb_io_in_1_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
  wire        _salloc_arb_io_in_5_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
  wire        _salloc_arb_io_in_8_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
  wire        _salloc_arb_io_in_9_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
  wire        _salloc_arb_io_out_0_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
  wire [9:0]  _salloc_arb_io_chosen_oh_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
  wire        _route_arbiter_io_in_1_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
  wire        _route_arbiter_io_in_5_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
  wire        _route_arbiter_io_in_8_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
  wire        _route_arbiter_io_in_9_ready;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
  wire        _route_arbiter_io_out_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
  wire [3:0]  _route_arbiter_io_out_bits_src_virt_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
  wire        _input_buffer_io_deq_0_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_0_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_0_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_1_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_1_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_1_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_1_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_2_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_2_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_2_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_3_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_3_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_3_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_4_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_4_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_4_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_5_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_5_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_5_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_5_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_6_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_6_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_6_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_7_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_7_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_7_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_8_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_8_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_8_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_8_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_9_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_9_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire        _input_buffer_io_deq_9_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  wire [72:0] _input_buffer_io_deq_9_bits_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  reg  [2:0]  states_1_g;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_1_vc_sel_3_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_1_vc_sel_2_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_1_vc_sel_1_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_1_vc_sel_1_1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_1_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_1_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_1_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_1_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_1_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_5_g;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_5_vc_sel_3_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_5_vc_sel_2_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_5_vc_sel_1_4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_5_vc_sel_1_5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_5_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_5_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_5_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_5_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_5_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_8_g;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_8_vc_sel_3_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_8_vc_sel_2_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_8_vc_sel_1_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_8_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_8_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_8_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_8_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_8_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_9_g;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_9_vc_sel_3_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_9_vc_sel_2_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_9_vc_sel_1_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg         states_9_vc_sel_1_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_9_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_9_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_9_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [2:0]  states_9_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  reg  [1:0]  states_9_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
  wire        _GEN = io_in_flit_0_valid & io_in_flit_0_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:205:30]
  wire        route_arbiter_io_in_1_valid = states_1_g == 3'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :229:22]
  wire        route_arbiter_io_in_5_valid = states_5_g == 3'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :229:22]
  wire        route_arbiter_io_in_8_valid = states_8_g == 3'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :229:22]
  wire        route_arbiter_io_in_9_valid = states_9_g == 3'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :229:22]
  reg  [9:0]  mask;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:250:21]
  wire [9:0]  _vcalloc_filter_T_3 = {vcalloc_vals_9, vcalloc_vals_8, 2'h0, vcalloc_vals_5, 3'h0, vcalloc_vals_1, 1'h0} & ~mask;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:250:21, :253:{80,87,89}, :266:32]
  wire [19:0] vcalloc_filter = _vcalloc_filter_T_3[0] ? 20'h1 : _vcalloc_filter_T_3[1] ? 20'h2 : _vcalloc_filter_T_3[2] ? 20'h4 : _vcalloc_filter_T_3[3] ? 20'h8 : _vcalloc_filter_T_3[4] ? 20'h10 : _vcalloc_filter_T_3[5] ? 20'h20 : _vcalloc_filter_T_3[6] ? 20'h40 : _vcalloc_filter_T_3[7] ? 20'h80 : _vcalloc_filter_T_3[8] ? 20'h100 : _vcalloc_filter_T_3[9] ? 20'h200 : vcalloc_vals_1 ? 20'h800 : vcalloc_vals_5 ? 20'h8000 : vcalloc_vals_8 ? 20'h40000 : {vcalloc_vals_9, 19'h0};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:253:87, :266:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:85:71]
  wire [9:0]  vcalloc_sel = vcalloc_filter[9:0] | vcalloc_filter[19:10];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:254:{35,58,76}, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire        io_vcalloc_req_valid_0 = vcalloc_vals_1 | vcalloc_vals_5 | vcalloc_vals_8 | vcalloc_vals_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:266:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59]
  assign vcalloc_vals_1 = states_1_g == 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :266:32]
  assign vcalloc_vals_5 = states_5_g == 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :266:32]
  assign vcalloc_vals_8 = states_8_g == 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :266:32]
  assign vcalloc_vals_9 = states_9_g == 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :266:32]
  wire        _GEN_0 = io_vcalloc_req_ready & io_vcalloc_req_valid_0;	// @[generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_1 = _GEN_0 & vcalloc_sel[1];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:254:58, :287:29, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
  wire        _GEN_2 = _GEN_0 & vcalloc_sel[5];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:254:58, :287:29, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
  wire        _GEN_3 = _GEN_0 & vcalloc_sel[8];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:254:58, :287:29, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
  wire        _GEN_4 = _GEN_0 & vcalloc_sel[9];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:254:58, :287:29, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
  `ifndef SYNTHESIS	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13]
    wire [5:0][2:0]  _GEN_5 = '{3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0};
    wire             _GEN_6 = _GEN & ~reset;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:205:30, :207:13]
    wire [15:0][2:0] _GEN_7 = {_GEN_5, {{states_9_g}, {states_8_g}, {3'h0}, {3'h0}, {states_5_g}, {3'h0}, {3'h0}, {3'h0}, {states_1_g}, {3'h0}}};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :208:27]
    always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13]
      if (_GEN_6 & io_in_flit_0_bits_virt_channel_id > 4'h9) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:{13,17}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13]
          $error("Assertion failed\n    at InputUnit.scala:207 assert(id < nVirtualChannels.U)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13]
      end
      if (_GEN_6 & (|_GEN_7[io_in_flit_0_bits_virt_channel_id])) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13, :208:{13,27}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:208:13]
          $error("Assertion failed\n    at InputUnit.scala:208 assert(states(id).g === g_i)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:208:13]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:208:13]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:208:13]
      end
      if (_route_arbiter_io_out_valid & ~reset & _GEN_7[_route_arbiter_io_out_bits_src_virt_id] != 3'h1) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :207:13, :208:27, :241:{11,25}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:241:11]
          $error("Assertion failed\n    at InputUnit.scala:241 assert(states(id).g === g_r)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:241:11]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:241:11]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:241:11]
      end
      if (_GEN_0 & vcalloc_sel[0] & ~reset) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13, :254:58, :287:29, :291:17, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_1 & ~reset & states_1_g != 3'h2) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :207:13, :266:32, :287:29, :291:17]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_0 & vcalloc_sel[2] & ~reset) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13, :254:58, :287:29, :291:17, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_0 & vcalloc_sel[3] & ~reset) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13, :254:58, :287:29, :291:17, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_0 & vcalloc_sel[4] & ~reset) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13, :254:58, :287:29, :291:17, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_2 & ~reset & states_5_g != 3'h2) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :207:13, :266:32, :287:29, :291:17]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_0 & vcalloc_sel[6] & ~reset) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13, :254:58, :287:29, :291:17, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_0 & vcalloc_sel[7] & ~reset) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:207:13, :254:58, :287:29, :291:17, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_3 & ~reset & states_8_g != 3'h2) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :207:13, :266:32, :287:29, :291:17]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
      if (_GEN_4 & ~reset & states_9_g != 3'h2) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :207:13, :266:32, :287:29, :291:17]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $error("Assertion failed\n    at InputUnit.scala:291 assert(states(i).g === g_v)\n");	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
        if (`STOP_COND_)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
          $fatal;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:291:17]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [11:0] _credit_available_T_6 = {states_1_vc_sel_3_0, states_1_vc_sel_2_0, 8'h0, states_1_vc_sel_1_1, states_1_vc_sel_1_0} & {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_9, io_out_credit_available_1_8, 2'h3, io_out_credit_available_1_5, io_out_credit_available_1_4, 2'h3, io_out_credit_available_1_1, io_out_credit_available_1_0};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :304:{40,47,73}]
  wire        salloc_arb_io_in_1_valid = states_1_g == 3'h3 & (|{_credit_available_T_6[11:10], _credit_available_T_6[1:0]}) & _input_buffer_io_deq_1_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :192:19, :304:{47,81}, :305:{22,30,50}]
  wire [7:0]  _credit_available_T_13 = {states_5_vc_sel_3_0, states_5_vc_sel_2_0, 4'h0, states_5_vc_sel_1_5, states_5_vc_sel_1_4} & {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_9, io_out_credit_available_1_8, 2'h3, io_out_credit_available_1_5, io_out_credit_available_1_4};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :304:{40,47,73}]
  wire        salloc_arb_io_in_5_valid = states_5_g == 3'h3 & (|{_credit_available_T_13[7:6], _credit_available_T_13[1:0]}) & _input_buffer_io_deq_5_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :192:19, :304:{47,81}, :305:{22,30,50}]
  wire [3:0]  _GEN_8 = {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_9, io_out_credit_available_1_8};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:304:73]
  wire [3:0]  _credit_available_T_20 = {states_8_vc_sel_3_0, states_8_vc_sel_2_0, 1'h0, states_8_vc_sel_1_8} & _GEN_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :304:{40,47,73}]
  wire        salloc_arb_io_in_8_valid = states_8_g == 3'h3 & (|{_credit_available_T_20[3:2], _credit_available_T_20[0]}) & _input_buffer_io_deq_8_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :192:19, :304:{47,81}, :305:{22,30,50}]
  wire        salloc_arb_io_in_9_valid = states_9_g == 3'h3 & (|({states_9_vc_sel_3_0, states_9_vc_sel_2_0, states_9_vc_sel_1_9, states_9_vc_sel_1_8} & _GEN_8)) & _input_buffer_io_deq_9_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :192:19, :304:{40,47,73,81}, :305:{22,30,50}]
  reg         salloc_outs_0_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg  [3:0]  salloc_outs_0_out_vid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg         salloc_outs_0_flit_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg         salloc_outs_0_flit_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg  [72:0] salloc_outs_0_flit_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg  [2:0]  salloc_outs_0_flit_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg  [2:0]  salloc_outs_0_flit_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg  [1:0]  salloc_outs_0_flit_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg  [2:0]  salloc_outs_0_flit_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  reg  [1:0]  salloc_outs_0_flit_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8]
  wire        _salloc_outs_0_valid_T = io_salloc_req_0_ready & _salloc_arb_io_out_0_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [15:0] _mask_T = 16'h1 << _route_arbiter_io_out_bits_src_virt_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :257:18]
  wire [2:0]  _states_g_T = io_in_flit_0_bits_flow_egress_node == 3'h3 ? 3'h2 : 3'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:209:57, :210:26]
  wire        _GEN_9 = io_in_flit_0_bits_virt_channel_id == 4'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:210:20]
  wire        _GEN_10 = _GEN & _GEN_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20]
  wire        _GEN_11 = io_in_flit_0_bits_virt_channel_id == 4'h5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:210:20]
  wire        _GEN_12 = _GEN & _GEN_11;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20]
  wire        _GEN_13 = io_in_flit_0_bits_virt_channel_id == 4'h8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:210:20]
  wire        _GEN_14 = _GEN & _GEN_13;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20]
  wire        _GEN_15 = io_in_flit_0_bits_virt_channel_id == 4'h9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:210:20]
  wire        _GEN_16 = _GEN & _GEN_15;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20]
  wire        _GEN_17 = io_in_flit_0_bits_flow_egress_node_id == 2'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:213:19]
  wire        _GEN_18 = io_in_flit_0_bits_flow_egress_node_id == 2'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:213:19]
  wire        _GEN_19 = _route_arbiter_io_out_bits_src_virt_id == 4'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :242:18]
  wire        _GEN_20 = _route_arbiter_io_out_bits_src_virt_id == 4'h5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :242:18]
  wire        _GEN_21 = _route_arbiter_io_out_bits_src_virt_id == 4'h8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :242:18]
  wire        _GEN_22 = _route_arbiter_io_out_bits_src_virt_id == 4'h9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :242:18]
  wire        _GEN_23 = _route_arbiter_io_out_valid & _GEN_19;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :239:29, :242:18, :244:25, src/main/scala/chisel3/util/MixedVec.scala:116:9]
  wire        _GEN_24 = _route_arbiter_io_out_valid & _GEN_20;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :239:29, :242:18, :244:25, src/main/scala/chisel3/util/MixedVec.scala:116:9]
  wire        _GEN_25 = _route_arbiter_io_out_valid & _GEN_21;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :239:29, :242:18, :244:25, src/main/scala/chisel3/util/MixedVec.scala:116:9]
  wire        _GEN_26 = _route_arbiter_io_out_valid & _GEN_22;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :239:29, :242:18, :244:25, src/main/scala/chisel3/util/MixedVec.scala:116:9]
  wire        _vc_sel_T_220 = _salloc_arb_io_chosen_oh_0[1] & states_1_vc_sel_1_1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  wire        _vc_sel_T_281 = _salloc_arb_io_chosen_oh_0[5] & states_5_vc_sel_1_4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  wire        _vc_sel_T_300 = _salloc_arb_io_chosen_oh_0[5] & states_5_vc_sel_1_5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  wire        _vc_sel_T_370 = _salloc_arb_io_chosen_oh_0[8] & states_8_vc_sel_1_8 | _salloc_arb_io_chosen_oh_0[9] & states_9_vc_sel_1_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  wire        _vc_sel_T_380 = _salloc_arb_io_chosen_oh_0[9] & states_9_vc_sel_1_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
    if (reset | _salloc_arb_io_in_1_ready & salloc_arb_io_in_1_valid & _input_buffer_io_deq_1_bits_tail)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :285:30, :296:26, :305:{30,50}, :309:{20,33}, :310:13, :395:23, :396:24, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_1_g <= 3'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_0 & vcalloc_sel[1] | vcalloc_vals_1 & vcalloc_sel[1] & io_vcalloc_req_ready)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:239:29, :254:58, :266:32, :270:{31,51,76,82}, :285:30, :287:29, :289:21, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
      states_1_g <= 3'h3;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_route_arbiter_io_out_valid & _GEN_19 | _route_arbiter_io_in_1_ready & route_arbiter_io_in_1_valid)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :229:22, :232:{21,27}, :239:29, :242:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_1_g <= 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_10)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_1_g <= _states_g_T;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :210:26]
    states_1_vc_sel_3_0 <= _GEN_1 ? io_vcalloc_resp_vc_sel_3_0 : ~_GEN_23 & (_GEN ? _GEN_18 & _GEN_9 | ~_GEN_9 & states_1_vc_sel_3_0 : states_1_vc_sel_3_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_1_vc_sel_2_0 <= _GEN_1 ? io_vcalloc_resp_vc_sel_2_0 : ~_GEN_23 & (_GEN ? _GEN_17 & _GEN_9 | ~_GEN_9 & states_1_vc_sel_2_0 : states_1_vc_sel_2_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_1_vc_sel_1_0 <= _GEN_1 ? io_vcalloc_resp_vc_sel_1_0 : _GEN_23 ? io_router_resp_vc_sel_1_0 : ~_GEN_10 & states_1_vc_sel_1_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20, :211:45, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_1_vc_sel_1_1 <= _GEN_1 ? io_vcalloc_resp_vc_sel_1_1 : _GEN_23 ? io_router_resp_vc_sel_1_1 : ~_GEN_10 & states_1_vc_sel_1_1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20, :211:45, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    if (_GEN_10) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_1_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_1_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_1_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_1_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_1_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    end
    if (reset | _salloc_arb_io_in_5_ready & salloc_arb_io_in_5_valid & _input_buffer_io_deq_5_bits_tail)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :285:30, :296:26, :305:{30,50}, :309:{20,33}, :310:13, :395:23, :396:24, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_5_g <= 3'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_0 & vcalloc_sel[5] | vcalloc_vals_5 & vcalloc_sel[5] & io_vcalloc_req_ready)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:239:29, :254:58, :266:32, :270:{31,51,76,82}, :285:30, :287:29, :289:21, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
      states_5_g <= 3'h3;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_route_arbiter_io_out_valid & _GEN_20 | _route_arbiter_io_in_5_ready & route_arbiter_io_in_5_valid)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :229:22, :232:{21,27}, :239:29, :242:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_5_g <= 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_12)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_5_g <= _states_g_T;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :210:26]
    states_5_vc_sel_3_0 <= _GEN_2 ? io_vcalloc_resp_vc_sel_3_0 : ~_GEN_24 & (_GEN ? _GEN_18 & _GEN_11 | ~_GEN_11 & states_5_vc_sel_3_0 : states_5_vc_sel_3_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_5_vc_sel_2_0 <= _GEN_2 ? io_vcalloc_resp_vc_sel_2_0 : ~_GEN_24 & (_GEN ? _GEN_17 & _GEN_11 | ~_GEN_11 & states_5_vc_sel_2_0 : states_5_vc_sel_2_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_5_vc_sel_1_4 <= _GEN_2 ? io_vcalloc_resp_vc_sel_1_4 : _GEN_24 ? io_router_resp_vc_sel_1_4 : ~_GEN_12 & states_5_vc_sel_1_4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20, :211:45, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_5_vc_sel_1_5 <= _GEN_2 ? io_vcalloc_resp_vc_sel_1_5 : _GEN_24 ? io_router_resp_vc_sel_1_5 : ~_GEN_12 & states_5_vc_sel_1_5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20, :211:45, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    if (_GEN_12) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_5_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_5_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_5_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_5_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_5_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    end
    if (reset | _salloc_arb_io_in_8_ready & salloc_arb_io_in_8_valid & _input_buffer_io_deq_8_bits_tail)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :285:30, :296:26, :305:{30,50}, :309:{20,33}, :310:13, :395:23, :396:24, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_8_g <= 3'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_0 & vcalloc_sel[8] | vcalloc_vals_8 & vcalloc_sel[8] & io_vcalloc_req_ready)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:239:29, :254:58, :266:32, :270:{31,51,76,82}, :285:30, :287:29, :289:21, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
      states_8_g <= 3'h3;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_route_arbiter_io_out_valid & _GEN_21 | _route_arbiter_io_in_8_ready & route_arbiter_io_in_8_valid)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :229:22, :232:{21,27}, :239:29, :242:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_8_g <= 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_14)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_8_g <= _states_g_T;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :210:26]
    states_8_vc_sel_3_0 <= _GEN_3 ? io_vcalloc_resp_vc_sel_3_0 : ~_GEN_25 & (_GEN ? _GEN_18 & _GEN_13 | ~_GEN_13 & states_8_vc_sel_3_0 : states_8_vc_sel_3_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_8_vc_sel_2_0 <= _GEN_3 ? io_vcalloc_resp_vc_sel_2_0 : ~_GEN_25 & (_GEN ? _GEN_17 & _GEN_13 | ~_GEN_13 & states_8_vc_sel_2_0 : states_8_vc_sel_2_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_8_vc_sel_1_8 <= _GEN_3 ? io_vcalloc_resp_vc_sel_1_8 : _GEN_25 ? io_router_resp_vc_sel_1_8 : ~_GEN_14 & states_8_vc_sel_1_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20, :211:45, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    if (_GEN_14) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_8_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_8_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_8_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_8_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_8_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    end
    if (reset | _salloc_arb_io_in_9_ready & salloc_arb_io_in_9_valid & _input_buffer_io_deq_9_bits_tail)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :285:30, :296:26, :305:{30,50}, :309:{20,33}, :310:13, :395:23, :396:24, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_9_g <= 3'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_0 & vcalloc_sel[9] | vcalloc_vals_9 & vcalloc_sel[9] & io_vcalloc_req_ready)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:239:29, :254:58, :266:32, :270:{31,51,76,82}, :285:30, :287:29, :289:21, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:32:36]
      states_9_g <= 3'h3;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_route_arbiter_io_out_valid & _GEN_22 | _route_arbiter_io_in_9_ready & route_arbiter_io_in_9_valid)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29, :205:58, :229:22, :232:{21,27}, :239:29, :242:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      states_9_g <= 3'h2;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    else if (_GEN_16)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_9_g <= _states_g_T;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :210:26]
    states_9_vc_sel_3_0 <= _GEN_4 ? io_vcalloc_resp_vc_sel_3_0 : ~_GEN_26 & (_GEN ? _GEN_18 & _GEN_15 | ~_GEN_15 & states_9_vc_sel_3_0 : states_9_vc_sel_3_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_9_vc_sel_2_0 <= _GEN_4 ? io_vcalloc_resp_vc_sel_2_0 : ~_GEN_26 & (_GEN ? _GEN_17 & _GEN_15 | ~_GEN_15 & states_9_vc_sel_2_0 : states_9_vc_sel_2_0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:{30,58}, :210:20, :211:45, :213:{19,63}, :214:44, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_9_vc_sel_1_8 <= _GEN_4 ? io_vcalloc_resp_vc_sel_1_8 : _GEN_26 ? io_router_resp_vc_sel_1_8 : ~_GEN_16 & states_9_vc_sel_1_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20, :211:45, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    states_9_vc_sel_1_9 <= _GEN_4 ? io_vcalloc_resp_vc_sel_1_9 : _GEN_26 ? io_router_resp_vc_sel_1_9 : ~_GEN_16 & states_9_vc_sel_1_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20, :211:45, :239:29, :244:25, :285:30, :287:29, src/main/scala/chisel3/util/MixedVec.scala:116:9]
    if (_GEN_16) begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :205:58, :210:20]
      states_9_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_9_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_9_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_9_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
      states_9_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    end
    salloc_outs_0_valid <= _salloc_outs_0_valid_T;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:336:8, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    salloc_outs_0_out_vid <= _salloc_arb_io_chosen_oh_0[1] & states_1_vc_sel_1_0 | _vc_sel_T_220 | _vc_sel_T_281 | _vc_sel_T_300 | _vc_sel_T_370 | _vc_sel_T_380 ? {|{_vc_sel_T_380, _vc_sel_T_370}, |{_vc_sel_T_300, _vc_sel_T_281}, 1'h0, _vc_sel_T_300 | _vc_sel_T_380 | _vc_sel_T_220} : 4'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, :336:8, :352:43, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36, src/main/scala/chisel3/util/OneHot.scala:30:18, :32:{10,14,28}]
    salloc_outs_0_flit_head <= _salloc_arb_io_chosen_oh_0[0] & _input_buffer_io_deq_0_bits_head | _salloc_arb_io_chosen_oh_0[1] & _input_buffer_io_deq_1_bits_head | _salloc_arb_io_chosen_oh_0[2] & _input_buffer_io_deq_2_bits_head | _salloc_arb_io_chosen_oh_0[3] & _input_buffer_io_deq_3_bits_head | _salloc_arb_io_chosen_oh_0[4] & _input_buffer_io_deq_4_bits_head | _salloc_arb_io_chosen_oh_0[5] & _input_buffer_io_deq_5_bits_head | _salloc_arb_io_chosen_oh_0[6] & _input_buffer_io_deq_6_bits_head | _salloc_arb_io_chosen_oh_0[7] & _input_buffer_io_deq_7_bits_head | _salloc_arb_io_chosen_oh_0[8] & _input_buffer_io_deq_8_bits_head | _salloc_arb_io_chosen_oh_0[9] & _input_buffer_io_deq_9_bits_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    salloc_outs_0_flit_tail <= _salloc_arb_io_chosen_oh_0[0] & _input_buffer_io_deq_0_bits_tail | _salloc_arb_io_chosen_oh_0[1] & _input_buffer_io_deq_1_bits_tail | _salloc_arb_io_chosen_oh_0[2] & _input_buffer_io_deq_2_bits_tail | _salloc_arb_io_chosen_oh_0[3] & _input_buffer_io_deq_3_bits_tail | _salloc_arb_io_chosen_oh_0[4] & _input_buffer_io_deq_4_bits_tail | _salloc_arb_io_chosen_oh_0[5] & _input_buffer_io_deq_5_bits_tail | _salloc_arb_io_chosen_oh_0[6] & _input_buffer_io_deq_6_bits_tail | _salloc_arb_io_chosen_oh_0[7] & _input_buffer_io_deq_7_bits_tail | _salloc_arb_io_chosen_oh_0[8] & _input_buffer_io_deq_8_bits_tail | _salloc_arb_io_chosen_oh_0[9] & _input_buffer_io_deq_9_bits_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    salloc_outs_0_flit_payload <= (_salloc_arb_io_chosen_oh_0[0] ? _input_buffer_io_deq_0_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[1] ? _input_buffer_io_deq_1_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[2] ? _input_buffer_io_deq_2_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[3] ? _input_buffer_io_deq_3_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[4] ? _input_buffer_io_deq_4_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[5] ? _input_buffer_io_deq_5_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[6] ? _input_buffer_io_deq_6_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[7] ? _input_buffer_io_deq_7_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[8] ? _input_buffer_io_deq_8_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[9] ? _input_buffer_io_deq_9_bits_payload : 73'h0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    salloc_outs_0_flit_flow_vnet_id <= (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_vnet_id : 3'h0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    salloc_outs_0_flit_flow_ingress_node <= (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_ingress_node : 3'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_ingress_node : 3'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_ingress_node : 3'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_ingress_node : 3'h0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    salloc_outs_0_flit_flow_ingress_node_id <= (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_ingress_node_id : 2'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_ingress_node_id : 2'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_ingress_node_id : 2'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_ingress_node_id : 2'h0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    salloc_outs_0_flit_flow_egress_node <= (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_egress_node : 3'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_egress_node : 3'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_egress_node : 3'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_egress_node : 3'h0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    salloc_outs_0_flit_flow_egress_node_id <= (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_egress_node_id : 2'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_egress_node_id : 2'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_egress_node_id : 2'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_egress_node_id : 2'h0);	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19, :296:26, :336:8, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
    if (reset)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
      mask <= 10'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:250:21]
    else if (_route_arbiter_io_out_valid)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
      mask <= _mask_T[9:0] - 10'h1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:250:21, :257:{18,53}]
    else if (vcalloc_vals_1 | vcalloc_vals_5 | vcalloc_vals_8 | vcalloc_vals_9)	// @[generators/constellation/src/main/scala/router/InputUnit.scala:266:32, generators/rocket-chip/src/main/scala/util/package.scala:81:59]
      mask <= {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, vcalloc_sel[0]} | {2{vcalloc_sel[1]}}} | {3{vcalloc_sel[2]}}} | {4{vcalloc_sel[3]}}} | {5{vcalloc_sel[4]}}} | {6{vcalloc_sel[5]}}} | {7{vcalloc_sel[6]}}} | {8{vcalloc_sel[7]}}} | {9{vcalloc_sel[8]}}} | {10{vcalloc_sel[9]}};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:250:21, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:18];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
    initial begin	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
        `INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
        end	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
        states_1_g = _RANDOM[5'h1][18:16];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_vc_sel_3_0 = _RANDOM[5'h1][19];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_vc_sel_2_0 = _RANDOM[5'h1][20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_vc_sel_1_0 = _RANDOM[5'h1][21];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_vc_sel_1_1 = _RANDOM[5'h1][22];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_flow_vnet_id = _RANDOM[5'h2][11:9];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_flow_ingress_node = _RANDOM[5'h2][14:12];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_flow_ingress_node_id = _RANDOM[5'h2][16:15];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_flow_egress_node = _RANDOM[5'h2][19:17];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_1_flow_egress_node_id = _RANDOM[5'h2][21:20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_g = _RANDOM[5'h7][18:16];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_vc_sel_3_0 = _RANDOM[5'h7][19];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_vc_sel_2_0 = _RANDOM[5'h7][20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_vc_sel_1_4 = _RANDOM[5'h7][25];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_vc_sel_1_5 = _RANDOM[5'h7][26];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_flow_vnet_id = _RANDOM[5'h8][11:9];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_flow_ingress_node = _RANDOM[5'h8][14:12];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_flow_ingress_node_id = _RANDOM[5'h8][16:15];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_flow_egress_node = _RANDOM[5'h8][19:17];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_5_flow_egress_node_id = _RANDOM[5'h8][21:20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_g = _RANDOM[5'hC][2:0];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_vc_sel_3_0 = _RANDOM[5'hC][3];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_vc_sel_2_0 = _RANDOM[5'hC][4];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_vc_sel_1_8 = _RANDOM[5'hC][13];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_flow_vnet_id = _RANDOM[5'hC][27:25];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_flow_ingress_node = _RANDOM[5'hC][30:28];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_flow_ingress_node_id = {_RANDOM[5'hC][31], _RANDOM[5'hD][0]};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_flow_egress_node = _RANDOM[5'hD][3:1];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_8_flow_egress_node_id = _RANDOM[5'hD][5:4];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_g = _RANDOM[5'hD][18:16];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_vc_sel_3_0 = _RANDOM[5'hD][19];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_vc_sel_2_0 = _RANDOM[5'hD][20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_vc_sel_1_8 = _RANDOM[5'hD][29];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_vc_sel_1_9 = _RANDOM[5'hD][30];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_flow_vnet_id = _RANDOM[5'hE][11:9];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_flow_ingress_node = _RANDOM[5'hE][14:12];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_flow_ingress_node_id = _RANDOM[5'hE][16:15];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_flow_egress_node = _RANDOM[5'hE][19:17];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        states_9_flow_egress_node_id = _RANDOM[5'hE][21:20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19]
        mask = _RANDOM[5'hF][9:0];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :250:21]
        salloc_outs_0_valid = _RANDOM[5'hF][10];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :250:21, :336:8]
        salloc_outs_0_out_vid = _RANDOM[5'hF][18:15];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :250:21, :336:8]
        salloc_outs_0_flit_head = _RANDOM[5'hF][19];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :250:21, :336:8]
        salloc_outs_0_flit_tail = _RANDOM[5'hF][20];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :250:21, :336:8]
        salloc_outs_0_flit_payload = {_RANDOM[5'hF][31:21], _RANDOM[5'h10], _RANDOM[5'h11][29:0]};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :250:21, :336:8]
        salloc_outs_0_flit_flow_vnet_id = {_RANDOM[5'h11][31:30], _RANDOM[5'h12][0]};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
        salloc_outs_0_flit_flow_ingress_node = _RANDOM[5'h12][3:1];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
        salloc_outs_0_flit_flow_ingress_node_id = _RANDOM[5'h12][5:4];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
        salloc_outs_0_flit_flow_egress_node = _RANDOM[5'h12][8:6];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
        salloc_outs_0_flit_flow_egress_node_id = _RANDOM[5'h12][10:9];	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  InputBuffer_6 input_buffer (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
    .clock                         (clock),
    .reset                         (reset),
    .io_enq_0_valid                (io_in_flit_0_valid),
    .io_enq_0_bits_head            (io_in_flit_0_bits_head),
    .io_enq_0_bits_tail            (io_in_flit_0_bits_tail),
    .io_enq_0_bits_payload         (io_in_flit_0_bits_payload),
    .io_enq_0_bits_virt_channel_id (io_in_flit_0_bits_virt_channel_id),
    .io_deq_0_bits_head            (_input_buffer_io_deq_0_bits_head),
    .io_deq_0_bits_tail            (_input_buffer_io_deq_0_bits_tail),
    .io_deq_0_bits_payload         (_input_buffer_io_deq_0_bits_payload),
    .io_deq_1_ready                (_salloc_arb_io_in_1_ready),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
    .io_deq_1_valid                (_input_buffer_io_deq_1_valid),
    .io_deq_1_bits_head            (_input_buffer_io_deq_1_bits_head),
    .io_deq_1_bits_tail            (_input_buffer_io_deq_1_bits_tail),
    .io_deq_1_bits_payload         (_input_buffer_io_deq_1_bits_payload),
    .io_deq_2_bits_head            (_input_buffer_io_deq_2_bits_head),
    .io_deq_2_bits_tail            (_input_buffer_io_deq_2_bits_tail),
    .io_deq_2_bits_payload         (_input_buffer_io_deq_2_bits_payload),
    .io_deq_3_bits_head            (_input_buffer_io_deq_3_bits_head),
    .io_deq_3_bits_tail            (_input_buffer_io_deq_3_bits_tail),
    .io_deq_3_bits_payload         (_input_buffer_io_deq_3_bits_payload),
    .io_deq_4_bits_head            (_input_buffer_io_deq_4_bits_head),
    .io_deq_4_bits_tail            (_input_buffer_io_deq_4_bits_tail),
    .io_deq_4_bits_payload         (_input_buffer_io_deq_4_bits_payload),
    .io_deq_5_ready                (_salloc_arb_io_in_5_ready),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
    .io_deq_5_valid                (_input_buffer_io_deq_5_valid),
    .io_deq_5_bits_head            (_input_buffer_io_deq_5_bits_head),
    .io_deq_5_bits_tail            (_input_buffer_io_deq_5_bits_tail),
    .io_deq_5_bits_payload         (_input_buffer_io_deq_5_bits_payload),
    .io_deq_6_bits_head            (_input_buffer_io_deq_6_bits_head),
    .io_deq_6_bits_tail            (_input_buffer_io_deq_6_bits_tail),
    .io_deq_6_bits_payload         (_input_buffer_io_deq_6_bits_payload),
    .io_deq_7_bits_head            (_input_buffer_io_deq_7_bits_head),
    .io_deq_7_bits_tail            (_input_buffer_io_deq_7_bits_tail),
    .io_deq_7_bits_payload         (_input_buffer_io_deq_7_bits_payload),
    .io_deq_8_ready                (_salloc_arb_io_in_8_ready),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
    .io_deq_8_valid                (_input_buffer_io_deq_8_valid),
    .io_deq_8_bits_head            (_input_buffer_io_deq_8_bits_head),
    .io_deq_8_bits_tail            (_input_buffer_io_deq_8_bits_tail),
    .io_deq_8_bits_payload         (_input_buffer_io_deq_8_bits_payload),
    .io_deq_9_ready                (_salloc_arb_io_in_9_ready),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
    .io_deq_9_valid                (_input_buffer_io_deq_9_valid),
    .io_deq_9_bits_head            (_input_buffer_io_deq_9_bits_head),
    .io_deq_9_bits_tail            (_input_buffer_io_deq_9_bits_tail),
    .io_deq_9_bits_payload         (_input_buffer_io_deq_9_bits_payload)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
  Arbiter10_RouteComputerReq route_arbiter (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
    .io_in_0_valid                     (1'h0),
    .io_in_0_bits_flow_vnet_id         (3'h0),
    .io_in_0_bits_flow_ingress_node    (3'h0),
    .io_in_0_bits_flow_ingress_node_id (2'h0),
    .io_in_0_bits_flow_egress_node     (3'h0),
    .io_in_0_bits_flow_egress_node_id  (2'h0),
    .io_in_1_ready                     (_route_arbiter_io_in_1_ready),
    .io_in_1_valid                     (route_arbiter_io_in_1_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:229:22]
    .io_in_1_bits_src_virt_id          (4'h1),
    .io_in_1_bits_flow_vnet_id         (states_1_flow_vnet_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_flow_ingress_node    (states_1_flow_ingress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_flow_ingress_node_id (states_1_flow_ingress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_flow_egress_node     (states_1_flow_egress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_flow_egress_node_id  (states_1_flow_egress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_2_ready                     (/* unused */),
    .io_in_2_valid                     (1'h0),
    .io_in_2_bits_src_virt_id          (4'h0),
    .io_in_2_bits_flow_vnet_id         (3'h0),
    .io_in_2_bits_flow_ingress_node    (3'h0),
    .io_in_2_bits_flow_ingress_node_id (2'h0),
    .io_in_2_bits_flow_egress_node     (3'h0),
    .io_in_2_bits_flow_egress_node_id  (2'h0),
    .io_in_3_ready                     (/* unused */),
    .io_in_3_valid                     (1'h0),
    .io_in_3_bits_src_virt_id          (4'h0),
    .io_in_3_bits_flow_vnet_id         (3'h0),
    .io_in_3_bits_flow_ingress_node    (3'h0),
    .io_in_3_bits_flow_ingress_node_id (2'h0),
    .io_in_3_bits_flow_egress_node     (3'h0),
    .io_in_3_bits_flow_egress_node_id  (2'h0),
    .io_in_4_ready                     (/* unused */),
    .io_in_4_valid                     (1'h0),
    .io_in_4_bits_src_virt_id          (4'h0),
    .io_in_4_bits_flow_vnet_id         (3'h0),
    .io_in_4_bits_flow_ingress_node    (3'h0),
    .io_in_4_bits_flow_ingress_node_id (2'h0),
    .io_in_4_bits_flow_egress_node     (3'h0),
    .io_in_4_bits_flow_egress_node_id  (2'h0),
    .io_in_5_ready                     (_route_arbiter_io_in_5_ready),
    .io_in_5_valid                     (route_arbiter_io_in_5_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:229:22]
    .io_in_5_bits_src_virt_id          (4'h5),
    .io_in_5_bits_flow_vnet_id         (states_5_flow_vnet_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_flow_ingress_node    (states_5_flow_ingress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_flow_ingress_node_id (states_5_flow_ingress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_flow_egress_node     (states_5_flow_egress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_flow_egress_node_id  (states_5_flow_egress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_6_ready                     (/* unused */),
    .io_in_6_valid                     (1'h0),
    .io_in_6_bits_src_virt_id          (4'h0),
    .io_in_6_bits_flow_vnet_id         (3'h0),
    .io_in_6_bits_flow_ingress_node    (3'h0),
    .io_in_6_bits_flow_ingress_node_id (2'h0),
    .io_in_6_bits_flow_egress_node     (3'h0),
    .io_in_6_bits_flow_egress_node_id  (2'h0),
    .io_in_7_ready                     (/* unused */),
    .io_in_7_valid                     (1'h0),
    .io_in_7_bits_src_virt_id          (4'h0),
    .io_in_7_bits_flow_vnet_id         (3'h0),
    .io_in_7_bits_flow_ingress_node    (3'h0),
    .io_in_7_bits_flow_ingress_node_id (2'h0),
    .io_in_7_bits_flow_egress_node     (3'h0),
    .io_in_7_bits_flow_egress_node_id  (2'h0),
    .io_in_8_ready                     (_route_arbiter_io_in_8_ready),
    .io_in_8_valid                     (route_arbiter_io_in_8_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:229:22]
    .io_in_8_bits_src_virt_id          (4'h8),
    .io_in_8_bits_flow_vnet_id         (states_8_flow_vnet_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_8_bits_flow_ingress_node    (states_8_flow_ingress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_8_bits_flow_ingress_node_id (states_8_flow_ingress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_8_bits_flow_egress_node     (states_8_flow_egress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_8_bits_flow_egress_node_id  (states_8_flow_egress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_ready                     (_route_arbiter_io_in_9_ready),
    .io_in_9_valid                     (route_arbiter_io_in_9_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:229:22]
    .io_in_9_bits_src_virt_id          (4'h9),
    .io_in_9_bits_flow_vnet_id         (states_9_flow_vnet_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_flow_ingress_node    (states_9_flow_ingress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_flow_ingress_node_id (states_9_flow_ingress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_flow_egress_node     (states_9_flow_egress_node),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_flow_egress_node_id  (states_9_flow_egress_node_id),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_out_valid                      (_route_arbiter_io_out_valid),
    .io_out_bits_src_virt_id           (_route_arbiter_io_out_bits_src_virt_id),
    .io_out_bits_flow_vnet_id          (io_router_req_bits_flow_vnet_id),
    .io_out_bits_flow_ingress_node     (io_router_req_bits_flow_ingress_node),
    .io_out_bits_flow_ingress_node_id  (io_router_req_bits_flow_ingress_node_id),
    .io_out_bits_flow_egress_node      (io_router_req_bits_flow_egress_node),
    .io_out_bits_flow_egress_node_id   (io_router_req_bits_flow_egress_node_id)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:187:29]
  SwitchArbiter salloc_arb (	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
    .clock                    (clock),
    .reset                    (reset),
    .io_in_1_ready            (_salloc_arb_io_in_1_ready),
    .io_in_1_valid            (salloc_arb_io_in_1_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:305:{30,50}]
    .io_in_1_bits_vc_sel_3_0  (states_1_vc_sel_3_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_vc_sel_2_0  (states_1_vc_sel_2_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_vc_sel_1_0  (states_1_vc_sel_1_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_vc_sel_1_1  (states_1_vc_sel_1_1),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_1_bits_vc_sel_0_1  (1'h0),
    .io_in_1_bits_tail        (_input_buffer_io_deq_1_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
    .io_in_2_ready            (/* unused */),
    .io_in_2_valid            (1'h0),
    .io_in_2_bits_vc_sel_3_0  (1'h0),
    .io_in_2_bits_vc_sel_2_0  (1'h0),
    .io_in_2_bits_vc_sel_1_2  (1'h0),
    .io_in_2_bits_vc_sel_0_2  (1'h0),
    .io_in_2_bits_tail        (1'h0),
    .io_in_3_ready            (/* unused */),
    .io_in_3_valid            (1'h0),
    .io_in_3_bits_vc_sel_3_0  (1'h0),
    .io_in_3_bits_vc_sel_2_0  (1'h0),
    .io_in_3_bits_vc_sel_1_2  (1'h0),
    .io_in_3_bits_vc_sel_1_3  (1'h0),
    .io_in_3_bits_vc_sel_0_2  (1'h0),
    .io_in_3_bits_vc_sel_0_3  (1'h0),
    .io_in_3_bits_tail        (1'h0),
    .io_in_5_ready            (_salloc_arb_io_in_5_ready),
    .io_in_5_valid            (salloc_arb_io_in_5_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:305:{30,50}]
    .io_in_5_bits_vc_sel_3_0  (states_5_vc_sel_3_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_vc_sel_2_0  (states_5_vc_sel_2_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_vc_sel_1_4  (states_5_vc_sel_1_4),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_vc_sel_1_5  (states_5_vc_sel_1_5),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_5_bits_vc_sel_0_5  (1'h0),
    .io_in_5_bits_tail        (_input_buffer_io_deq_5_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
    .io_in_6_ready            (/* unused */),
    .io_in_6_valid            (1'h0),
    .io_in_6_bits_vc_sel_3_0  (1'h0),
    .io_in_6_bits_vc_sel_2_0  (1'h0),
    .io_in_6_bits_vc_sel_1_6  (1'h0),
    .io_in_6_bits_vc_sel_0_6  (1'h0),
    .io_in_6_bits_tail        (1'h0),
    .io_in_7_ready            (/* unused */),
    .io_in_7_valid            (1'h0),
    .io_in_7_bits_vc_sel_3_0  (1'h0),
    .io_in_7_bits_vc_sel_2_0  (1'h0),
    .io_in_7_bits_vc_sel_1_6  (1'h0),
    .io_in_7_bits_vc_sel_1_7  (1'h0),
    .io_in_7_bits_vc_sel_0_6  (1'h0),
    .io_in_7_bits_vc_sel_0_7  (1'h0),
    .io_in_7_bits_tail        (1'h0),
    .io_in_8_ready            (_salloc_arb_io_in_8_ready),
    .io_in_8_valid            (salloc_arb_io_in_8_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:305:{30,50}]
    .io_in_8_bits_vc_sel_3_0  (states_8_vc_sel_3_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_8_bits_vc_sel_2_0  (states_8_vc_sel_2_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_8_bits_vc_sel_1_8  (states_8_vc_sel_1_8),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_8_bits_tail        (_input_buffer_io_deq_8_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
    .io_in_9_ready            (_salloc_arb_io_in_9_ready),
    .io_in_9_valid            (salloc_arb_io_in_9_valid),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:305:{30,50}]
    .io_in_9_bits_vc_sel_3_0  (states_9_vc_sel_3_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_vc_sel_2_0  (states_9_vc_sel_2_0),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_vc_sel_1_8  (states_9_vc_sel_1_8),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_vc_sel_1_9  (states_9_vc_sel_1_9),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:192:19]
    .io_in_9_bits_vc_sel_0_9  (1'h0),
    .io_in_9_bits_tail        (_input_buffer_io_deq_9_bits_tail),	// @[generators/constellation/src/main/scala/router/InputUnit.scala:181:28]
    .io_out_0_ready           (io_salloc_req_0_ready),
    .io_out_0_valid           (_salloc_arb_io_out_0_valid),
    .io_out_0_bits_vc_sel_3_0 (io_salloc_req_0_bits_vc_sel_3_0),
    .io_out_0_bits_vc_sel_2_0 (io_salloc_req_0_bits_vc_sel_2_0),
    .io_out_0_bits_vc_sel_1_0 (io_salloc_req_0_bits_vc_sel_1_0),
    .io_out_0_bits_vc_sel_1_1 (io_salloc_req_0_bits_vc_sel_1_1),
    .io_out_0_bits_vc_sel_1_2 (io_salloc_req_0_bits_vc_sel_1_2),
    .io_out_0_bits_vc_sel_1_3 (io_salloc_req_0_bits_vc_sel_1_3),
    .io_out_0_bits_vc_sel_1_4 (io_salloc_req_0_bits_vc_sel_1_4),
    .io_out_0_bits_vc_sel_1_5 (io_salloc_req_0_bits_vc_sel_1_5),
    .io_out_0_bits_vc_sel_1_6 (io_salloc_req_0_bits_vc_sel_1_6),
    .io_out_0_bits_vc_sel_1_7 (io_salloc_req_0_bits_vc_sel_1_7),
    .io_out_0_bits_vc_sel_1_8 (io_salloc_req_0_bits_vc_sel_1_8),
    .io_out_0_bits_vc_sel_1_9 (io_salloc_req_0_bits_vc_sel_1_9),
    .io_out_0_bits_vc_sel_0_1 (io_salloc_req_0_bits_vc_sel_0_1),
    .io_out_0_bits_vc_sel_0_2 (io_salloc_req_0_bits_vc_sel_0_2),
    .io_out_0_bits_vc_sel_0_3 (io_salloc_req_0_bits_vc_sel_0_3),
    .io_out_0_bits_vc_sel_0_5 (io_salloc_req_0_bits_vc_sel_0_5),
    .io_out_0_bits_vc_sel_0_6 (io_salloc_req_0_bits_vc_sel_0_6),
    .io_out_0_bits_vc_sel_0_7 (io_salloc_req_0_bits_vc_sel_0_7),
    .io_out_0_bits_vc_sel_0_9 (io_salloc_req_0_bits_vc_sel_0_9),
    .io_out_0_bits_tail       (io_salloc_req_0_bits_tail),
    .io_chosen_oh_0           (_salloc_arb_io_chosen_oh_0)
  );	// @[generators/constellation/src/main/scala/router/InputUnit.scala:296:26]
  assign io_router_req_bits_src_virt_id = _route_arbiter_io_out_bits_src_virt_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :187:29]
  assign io_vcalloc_req_valid = io_vcalloc_req_valid_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, generators/rocket-chip/src/main/scala/util/package.scala:81:59]
  assign io_vcalloc_req_bits_vc_sel_3_0 = vcalloc_sel[1] & states_1_vc_sel_3_0 | vcalloc_sel[5] & states_5_vc_sel_3_0 | vcalloc_sel[8] & states_8_vc_sel_3_0 | vcalloc_sel[9] & states_9_vc_sel_3_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_vcalloc_req_bits_vc_sel_2_0 = vcalloc_sel[1] & states_1_vc_sel_2_0 | vcalloc_sel[5] & states_5_vc_sel_2_0 | vcalloc_sel[8] & states_8_vc_sel_2_0 | vcalloc_sel[9] & states_9_vc_sel_2_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_vcalloc_req_bits_vc_sel_1_0 = vcalloc_sel[1] & states_1_vc_sel_1_0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_vcalloc_req_bits_vc_sel_1_1 = vcalloc_sel[1] & states_1_vc_sel_1_1;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_vcalloc_req_bits_vc_sel_1_4 = vcalloc_sel[5] & states_5_vc_sel_1_4;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_vcalloc_req_bits_vc_sel_1_5 = vcalloc_sel[5] & states_5_vc_sel_1_5;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_vcalloc_req_bits_vc_sel_1_8 = vcalloc_sel[8] & states_8_vc_sel_1_8 | vcalloc_sel[9] & states_9_vc_sel_1_8;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_vcalloc_req_bits_vc_sel_1_9 = vcalloc_sel[9] & states_9_vc_sel_1_9;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :192:19, :254:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_salloc_req_0_valid = _salloc_arb_io_out_0_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :296:26]
  assign io_out_0_valid = salloc_outs_0_valid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_head = salloc_outs_0_flit_head;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_tail = salloc_outs_0_flit_tail;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_payload = salloc_outs_0_flit_payload;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_flow_vnet_id = salloc_outs_0_flit_flow_vnet_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_flow_ingress_node = salloc_outs_0_flit_flow_ingress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_flow_ingress_node_id = salloc_outs_0_flit_flow_ingress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_flow_egress_node = salloc_outs_0_flit_flow_egress_node;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_flit_flow_egress_node_id = salloc_outs_0_flit_flow_egress_node_id;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_out_0_bits_out_virt_channel = salloc_outs_0_out_vid;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :336:8]
  assign io_debug_va_stall = {3'h0, vcalloc_vals_1} + {1'h0, {2'h0, vcalloc_vals_5} + {1'h0, {1'h0, vcalloc_vals_8} + {1'h0, vcalloc_vals_9}}} - {3'h0, io_vcalloc_req_ready};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :266:32, :283:{32,47}]
  assign io_debug_sa_stall = {3'h0, salloc_arb_io_in_1_valid & ~_salloc_arb_io_in_1_ready} + {1'h0, {2'h0, salloc_arb_io_in_5_valid & ~_salloc_arb_io_in_5_ready} + {1'h0, {1'h0, salloc_arb_io_in_8_valid & ~_salloc_arb_io_in_8_ready} + {1'h0, salloc_arb_io_in_9_valid & ~_salloc_arb_io_in_9_ready}}};	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :296:26, :305:{30,50}, :319:{32,67,70}]
  assign io_in_credit_return = _salloc_outs_0_valid_T ? _salloc_arb_io_chosen_oh_0 : 10'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :296:26, :340:8, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_in_vc_free = _salloc_outs_0_valid_T & (_salloc_arb_io_chosen_oh_0[0] & _input_buffer_io_deq_0_bits_tail | _salloc_arb_io_chosen_oh_0[1] & _input_buffer_io_deq_1_bits_tail | _salloc_arb_io_chosen_oh_0[2] & _input_buffer_io_deq_2_bits_tail | _salloc_arb_io_chosen_oh_0[3] & _input_buffer_io_deq_3_bits_tail | _salloc_arb_io_chosen_oh_0[4] & _input_buffer_io_deq_4_bits_tail | _salloc_arb_io_chosen_oh_0[5] & _input_buffer_io_deq_5_bits_tail | _salloc_arb_io_chosen_oh_0[6] & _input_buffer_io_deq_6_bits_tail | _salloc_arb_io_chosen_oh_0[7] & _input_buffer_io_deq_7_bits_tail | _salloc_arb_io_chosen_oh_0[8] & _input_buffer_io_deq_8_bits_tail | _salloc_arb_io_chosen_oh_0[9] & _input_buffer_io_deq_9_bits_tail) ? _salloc_arb_io_chosen_oh_0 : 10'h0;	// @[generators/constellation/src/main/scala/router/InputUnit.scala:158:7, :181:28, :296:26, :343:{8,16}, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
endmodule

