// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SwitchArbiter_2(	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
  input        clock,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
  input        reset,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
  output       io_in_0_ready,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_valid,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_0_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_0_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_0_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_0_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_0_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_0_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_vc_sel_0_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_0_bits_tail,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_in_1_ready,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_valid,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_0_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_0_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_0_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_0_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_0_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_0_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_vc_sel_0_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_1_bits_tail,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_in_2_ready,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_valid,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_0_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_0_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_0_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_0_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_0_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_0_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_vc_sel_0_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_2_bits_tail,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_in_3_ready,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_valid,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_0_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_0_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_0_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_0_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_0_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_0_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_vc_sel_0_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_3_bits_tail,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_in_4_ready,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_valid,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_0_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_0_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_0_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_0_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_0_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_0_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_vc_sel_0_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  input        io_in_4_bits_tail,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_valid,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_3_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_2_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_0,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_4,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_8,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_1_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_0_1,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_0_2,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_0_3,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_0_5,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_0_6,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_0_7,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_vc_sel_0_9,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output       io_out_0_bits_tail,	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
  output [4:0] io_chosen_oh_0	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:18:14]
);

  reg  [4:0] lock_0;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:24:38]
  wire [4:0] unassigned = {io_in_4_valid, io_in_3_valid, io_in_2_valid, io_in_1_valid, io_in_0_valid} & ~lock_0;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:24:38, :25:{23,52,54}]
  reg  [4:0] mask;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:27:21]
  wire [4:0] _sel_T_1 = unassigned & ~mask;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:25:52, :27:21, :30:{58,60}]
  wire [9:0] sel = _sel_T_1[0] ? 10'h1 : _sel_T_1[1] ? 10'h2 : _sel_T_1[2] ? 10'h4 : _sel_T_1[3] ? 10'h8 : _sel_T_1[4] ? 10'h10 : unassigned[0] ? 10'h20 : unassigned[1] ? 10'h40 : unassigned[2] ? 10'h80 : unassigned[3] ? 10'h100 : {unassigned[4], 9'h0};	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:25:52, :30:58, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:85:71]
  wire [4:0] in_valids = {io_in_4_valid, io_in_3_valid, io_in_2_valid, io_in_1_valid, io_in_0_valid};	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:41:24]
  wire [4:0] chosen = (|(in_valids & lock_0)) ? lock_0 : sel[4:0] | sel[9:5];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:24:38, :32:{23,30}, :41:24, :42:{21,33,55}, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [4:0] _io_out_0_valid_T = in_valids & chosen;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:41:24, :42:21, :44:35]
  wire [3:0] _GEN = chosen[3:0] | chosen[4:1];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:42:21, :58:{55,71}]
  wire [2:0] _GEN_0 = _GEN[2:0] | chosen[4:2];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:42:21, :58:{55,71}]
  wire [1:0] _GEN_1 = _GEN_0[1:0] | chosen[4:3];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:42:21, :58:{55,71}]
  always @(posedge clock) begin	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
    if (reset) begin	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
      lock_0 <= 5'h0;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:24:38]
      mask <= 5'h0;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:27:21]
    end
    else begin	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
      if (|_io_out_0_valid_T)	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:44:{35,45}]
        lock_0 <= chosen & ~{io_in_4_bits_tail, io_in_3_bits_tail, io_in_2_bits_tail, io_in_1_bits_tail, io_in_0_bits_tail};	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:24:38, :39:21, :42:21, :53:{25,27}]
      mask <= (|_io_out_0_valid_T) ? {chosen[4], _GEN[3], _GEN_0[2], _GEN_1[1], _GEN_1[0] | chosen[4]} : (&mask) ? 5'h0 : {mask[3:0], 1'h1};	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :27:21, :42:21, :44:{35,45}, :57:25, :58:{10,55,71}, :60:{10,16,23,49}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
    initial begin	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
        `INIT_RANDOM_PROLOG_	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
        lock_0 = _RANDOM[/*Zero width*/ 1'b0][4:0];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :24:38]
        mask = _RANDOM[/*Zero width*/ 1'b0][9:5];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :24:38, :27:21]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_ready = chosen[0];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:32:36]
  assign io_in_1_ready = chosen[1];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:32:36]
  assign io_in_2_ready = chosen[2];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:32:36]
  assign io_in_3_ready = chosen[3];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:32:36]
  assign io_in_4_ready = chosen[4];	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:32:36]
  assign io_out_0_valid = |_io_out_0_valid_T;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :44:{35,45}]
  assign io_out_0_bits_vc_sel_3_0 = chosen[0] & io_in_0_bits_vc_sel_3_0 | chosen[1] & io_in_1_bits_vc_sel_3_0 | chosen[2] & io_in_2_bits_vc_sel_3_0 | chosen[3] & io_in_3_bits_vc_sel_3_0 | chosen[4] & io_in_4_bits_vc_sel_3_0;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_2_0 = chosen[0] & io_in_0_bits_vc_sel_2_0 | chosen[1] & io_in_1_bits_vc_sel_2_0 | chosen[2] & io_in_2_bits_vc_sel_2_0 | chosen[3] & io_in_3_bits_vc_sel_2_0 | chosen[4] & io_in_4_bits_vc_sel_2_0;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_0 = chosen[0] & io_in_0_bits_vc_sel_1_0 | chosen[1] & io_in_1_bits_vc_sel_1_0 | chosen[2] & io_in_2_bits_vc_sel_1_0 | chosen[3] & io_in_3_bits_vc_sel_1_0 | chosen[4] & io_in_4_bits_vc_sel_1_0;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_1 = chosen[0] & io_in_0_bits_vc_sel_1_1 | chosen[1] & io_in_1_bits_vc_sel_1_1 | chosen[2] & io_in_2_bits_vc_sel_1_1 | chosen[3] & io_in_3_bits_vc_sel_1_1 | chosen[4] & io_in_4_bits_vc_sel_1_1;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_2 = chosen[0] & io_in_0_bits_vc_sel_1_2 | chosen[1] & io_in_1_bits_vc_sel_1_2 | chosen[2] & io_in_2_bits_vc_sel_1_2 | chosen[3] & io_in_3_bits_vc_sel_1_2 | chosen[4] & io_in_4_bits_vc_sel_1_2;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_3 = chosen[0] & io_in_0_bits_vc_sel_1_3 | chosen[1] & io_in_1_bits_vc_sel_1_3 | chosen[2] & io_in_2_bits_vc_sel_1_3 | chosen[3] & io_in_3_bits_vc_sel_1_3 | chosen[4] & io_in_4_bits_vc_sel_1_3;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_4 = chosen[0] & io_in_0_bits_vc_sel_1_4 | chosen[1] & io_in_1_bits_vc_sel_1_4 | chosen[2] & io_in_2_bits_vc_sel_1_4 | chosen[3] & io_in_3_bits_vc_sel_1_4 | chosen[4] & io_in_4_bits_vc_sel_1_4;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_5 = chosen[0] & io_in_0_bits_vc_sel_1_5 | chosen[1] & io_in_1_bits_vc_sel_1_5 | chosen[2] & io_in_2_bits_vc_sel_1_5 | chosen[3] & io_in_3_bits_vc_sel_1_5 | chosen[4] & io_in_4_bits_vc_sel_1_5;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_6 = chosen[0] & io_in_0_bits_vc_sel_1_6 | chosen[1] & io_in_1_bits_vc_sel_1_6 | chosen[2] & io_in_2_bits_vc_sel_1_6 | chosen[3] & io_in_3_bits_vc_sel_1_6 | chosen[4] & io_in_4_bits_vc_sel_1_6;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_7 = chosen[0] & io_in_0_bits_vc_sel_1_7 | chosen[1] & io_in_1_bits_vc_sel_1_7 | chosen[2] & io_in_2_bits_vc_sel_1_7 | chosen[3] & io_in_3_bits_vc_sel_1_7 | chosen[4] & io_in_4_bits_vc_sel_1_7;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_8 = chosen[0] & io_in_0_bits_vc_sel_1_8 | chosen[1] & io_in_1_bits_vc_sel_1_8 | chosen[2] & io_in_2_bits_vc_sel_1_8 | chosen[3] & io_in_3_bits_vc_sel_1_8 | chosen[4] & io_in_4_bits_vc_sel_1_8;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_1_9 = chosen[0] & io_in_0_bits_vc_sel_1_9 | chosen[1] & io_in_1_bits_vc_sel_1_9 | chosen[2] & io_in_2_bits_vc_sel_1_9 | chosen[3] & io_in_3_bits_vc_sel_1_9 | chosen[4] & io_in_4_bits_vc_sel_1_9;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_0_1 = chosen[0] & io_in_0_bits_vc_sel_0_1 | chosen[1] & io_in_1_bits_vc_sel_0_1 | chosen[2] & io_in_2_bits_vc_sel_0_1 | chosen[3] & io_in_3_bits_vc_sel_0_1 | chosen[4] & io_in_4_bits_vc_sel_0_1;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_0_2 = chosen[0] & io_in_0_bits_vc_sel_0_2 | chosen[1] & io_in_1_bits_vc_sel_0_2 | chosen[2] & io_in_2_bits_vc_sel_0_2 | chosen[3] & io_in_3_bits_vc_sel_0_2 | chosen[4] & io_in_4_bits_vc_sel_0_2;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_0_3 = chosen[0] & io_in_0_bits_vc_sel_0_3 | chosen[1] & io_in_1_bits_vc_sel_0_3 | chosen[2] & io_in_2_bits_vc_sel_0_3 | chosen[3] & io_in_3_bits_vc_sel_0_3 | chosen[4] & io_in_4_bits_vc_sel_0_3;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_0_5 = chosen[0] & io_in_0_bits_vc_sel_0_5 | chosen[1] & io_in_1_bits_vc_sel_0_5 | chosen[2] & io_in_2_bits_vc_sel_0_5 | chosen[3] & io_in_3_bits_vc_sel_0_5 | chosen[4] & io_in_4_bits_vc_sel_0_5;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_0_6 = chosen[0] & io_in_0_bits_vc_sel_0_6 | chosen[1] & io_in_1_bits_vc_sel_0_6 | chosen[2] & io_in_2_bits_vc_sel_0_6 | chosen[3] & io_in_3_bits_vc_sel_0_6 | chosen[4] & io_in_4_bits_vc_sel_0_6;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_0_7 = chosen[0] & io_in_0_bits_vc_sel_0_7 | chosen[1] & io_in_1_bits_vc_sel_0_7 | chosen[2] & io_in_2_bits_vc_sel_0_7 | chosen[3] & io_in_3_bits_vc_sel_0_7 | chosen[4] & io_in_4_bits_vc_sel_0_7;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_vc_sel_0_9 = chosen[0] & io_in_0_bits_vc_sel_0_9 | chosen[1] & io_in_1_bits_vc_sel_0_9 | chosen[2] & io_in_2_bits_vc_sel_0_9 | chosen[3] & io_in_3_bits_vc_sel_0_9 | chosen[4] & io_in_4_bits_vc_sel_0_9;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_out_0_bits_tail = chosen[0] & io_in_0_bits_tail | chosen[1] & io_in_1_bits_tail | chosen[2] & io_in_2_bits_tail | chosen[3] & io_in_3_bits_tail | chosen[4] & io_in_4_bits_tail;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_chosen_oh_0 = chosen;	// @[generators/constellation/src/main/scala/router/SwitchAllocator.scala:17:7, :42:21]
endmodule

