// Generated by CIRCT firtool-1.75.0
module TLBToNoC(	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:133:7]
  input  clock,	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:133:7]
  input  reset,	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:133:7]
  output io_flit_valid	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14]
);

  Queue1_TLBundleB_a32d64s4k2z4c q (	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:26:17]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (/* unused */),
    .io_enq_valid        (1'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17, :50:22, :51:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_enq_bits_opcode  (3'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17]
    .io_enq_bits_param   (2'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17]
    .io_enq_bits_size    (4'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17]
    .io_enq_bits_source  (4'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17]
    .io_enq_bits_address (32'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17]
    .io_enq_bits_mask    (8'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17]
    .io_deq_ready        (1'h0),	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:19:14, :26:17, :50:22, :51:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_deq_valid        (io_flit_valid),
    .io_deq_bits_opcode  (/* unused */),
    .io_deq_bits_param   (/* unused */),
    .io_deq_bits_size    (/* unused */),
    .io_deq_bits_source  (/* unused */),
    .io_deq_bits_address (/* unused */),
    .io_deq_bits_mask    (/* unused */),
    .io_deq_bits_data    (/* unused */),
    .io_deq_bits_corrupt (/* unused */)
  );	// @[generators/constellation/src/main/scala/protocol/TilelinkAdapters.scala:26:17]
endmodule

