// Generated by CIRCT firtool-1.75.0
module TLNoC(	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:546:25]
  input         clock,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:546:25]
  input         reset,	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:546:25]
  output        auto_in_3_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_3_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_3_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_3_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_3_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_3_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_3_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_3_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_3_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_3_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_3_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_3_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_3_b_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_3_b_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_3_b_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_3_b_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_in_3_b_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_in_3_b_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_3_b_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_3_b_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_3_c_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_3_c_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_3_c_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_3_c_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_3_c_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_3_c_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_3_c_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_3_c_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_3_c_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_3_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_3_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_3_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_3_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_3_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_3_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_3_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_3_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_3_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_3_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_3_e_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_3_e_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_3_e_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_2_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_2_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_2_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_2_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_2_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_2_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_2_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_2_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_2_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_2_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_2_b_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_2_b_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_2_b_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_2_b_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_in_2_b_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_in_2_b_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_2_b_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_b_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_c_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_2_c_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_2_c_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_2_c_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_2_c_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_2_c_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_2_c_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_2_c_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_2_c_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_2_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_2_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_2_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_2_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_2_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_2_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_2_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_2_e_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_2_e_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_2_e_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_1_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_1_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_1_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_1_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_1_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_1_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_1_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_1_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_1_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_1_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_1_b_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_1_b_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_1_b_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_1_b_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_in_1_b_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_in_1_b_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_1_b_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_b_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_c_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_1_c_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_1_c_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_1_c_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_1_c_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_1_c_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_1_c_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_1_c_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_1_c_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_1_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_1_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_1_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_1_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_1_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_1_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_1_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_1_e_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_1_e_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_1_e_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_0_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_0_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_0_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_0_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_0_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_0_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_0_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_0_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_0_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_0_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_0_b_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_0_b_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_0_b_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_0_b_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_in_0_b_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_in_0_b_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_0_b_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_b_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_c_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_0_c_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_0_c_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_0_c_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_0_c_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_0_c_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_0_c_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_0_c_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_0_c_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_0_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_0_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_0_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_in_0_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_0_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_0_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_0_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_0_e_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_0_e_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_0_e_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_1_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_1_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_1_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_1_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_1_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_out_1_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_out_1_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_out_1_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_out_1_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_1_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_1_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_out_1_b_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_out_1_b_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_out_1_b_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_1_c_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_1_c_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_1_c_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_1_c_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_1_c_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_out_1_c_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_out_1_c_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_out_1_c_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_1_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_1_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_out_1_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_out_1_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_out_1_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_out_1_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_out_1_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_1_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_out_1_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_1_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_1_e_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_out_1_e_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_0_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_0_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_0_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_out_0_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_out_0_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_out_0_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [30:0] auto_out_0_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_out_0_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_out_0_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_0_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_out_0_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_0_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_out_0_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_out_0_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_out_0_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_out_0_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_0_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_0_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_out_0_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_out_0_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  ProtocolNoC noc (	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:561:21]
    .clock                              (clock),
    .reset                              (reset),
    .io_protocol_0_in_3_a_ready         (auto_in_3_a_ready),
    .io_protocol_0_in_3_a_valid         (auto_in_3_a_valid),
    .io_protocol_0_in_3_a_bits_opcode   (auto_in_3_a_bits_opcode),
    .io_protocol_0_in_3_a_bits_param    (auto_in_3_a_bits_param),
    .io_protocol_0_in_3_a_bits_size     (auto_in_3_a_bits_size),
    .io_protocol_0_in_3_a_bits_source   (auto_in_3_a_bits_source),
    .io_protocol_0_in_3_a_bits_address  (auto_in_3_a_bits_address),
    .io_protocol_0_in_3_a_bits_mask     (auto_in_3_a_bits_mask),
    .io_protocol_0_in_3_a_bits_data     (auto_in_3_a_bits_data),
    .io_protocol_0_in_3_a_bits_corrupt  (auto_in_3_a_bits_corrupt),
    .io_protocol_0_in_3_b_ready         (auto_in_3_b_ready),
    .io_protocol_0_in_3_b_valid         (auto_in_3_b_valid),
    .io_protocol_0_in_3_b_bits_opcode   (auto_in_3_b_bits_opcode),
    .io_protocol_0_in_3_b_bits_param    (auto_in_3_b_bits_param),
    .io_protocol_0_in_3_b_bits_size     (auto_in_3_b_bits_size),
    .io_protocol_0_in_3_b_bits_source   (auto_in_3_b_bits_source),
    .io_protocol_0_in_3_b_bits_address  (auto_in_3_b_bits_address),
    .io_protocol_0_in_3_b_bits_mask     (auto_in_3_b_bits_mask),
    .io_protocol_0_in_3_b_bits_data     (auto_in_3_b_bits_data),
    .io_protocol_0_in_3_b_bits_corrupt  (auto_in_3_b_bits_corrupt),
    .io_protocol_0_in_3_c_ready         (auto_in_3_c_ready),
    .io_protocol_0_in_3_c_valid         (auto_in_3_c_valid),
    .io_protocol_0_in_3_c_bits_opcode   (auto_in_3_c_bits_opcode),
    .io_protocol_0_in_3_c_bits_param    (auto_in_3_c_bits_param),
    .io_protocol_0_in_3_c_bits_size     (auto_in_3_c_bits_size),
    .io_protocol_0_in_3_c_bits_source   (auto_in_3_c_bits_source),
    .io_protocol_0_in_3_c_bits_address  (auto_in_3_c_bits_address),
    .io_protocol_0_in_3_c_bits_data     (auto_in_3_c_bits_data),
    .io_protocol_0_in_3_c_bits_corrupt  (auto_in_3_c_bits_corrupt),
    .io_protocol_0_in_3_d_ready         (auto_in_3_d_ready),
    .io_protocol_0_in_3_d_valid         (auto_in_3_d_valid),
    .io_protocol_0_in_3_d_bits_opcode   (auto_in_3_d_bits_opcode),
    .io_protocol_0_in_3_d_bits_param    (auto_in_3_d_bits_param),
    .io_protocol_0_in_3_d_bits_size     (auto_in_3_d_bits_size),
    .io_protocol_0_in_3_d_bits_source   (auto_in_3_d_bits_source),
    .io_protocol_0_in_3_d_bits_sink     (auto_in_3_d_bits_sink),
    .io_protocol_0_in_3_d_bits_denied   (auto_in_3_d_bits_denied),
    .io_protocol_0_in_3_d_bits_data     (auto_in_3_d_bits_data),
    .io_protocol_0_in_3_d_bits_corrupt  (auto_in_3_d_bits_corrupt),
    .io_protocol_0_in_3_e_ready         (auto_in_3_e_ready),
    .io_protocol_0_in_3_e_valid         (auto_in_3_e_valid),
    .io_protocol_0_in_3_e_bits_sink     (auto_in_3_e_bits_sink),
    .io_protocol_0_in_2_a_ready         (auto_in_2_a_ready),
    .io_protocol_0_in_2_a_valid         (auto_in_2_a_valid),
    .io_protocol_0_in_2_a_bits_opcode   (auto_in_2_a_bits_opcode),
    .io_protocol_0_in_2_a_bits_param    (auto_in_2_a_bits_param),
    .io_protocol_0_in_2_a_bits_size     (auto_in_2_a_bits_size),
    .io_protocol_0_in_2_a_bits_source   (auto_in_2_a_bits_source),
    .io_protocol_0_in_2_a_bits_address  (auto_in_2_a_bits_address),
    .io_protocol_0_in_2_a_bits_mask     (auto_in_2_a_bits_mask),
    .io_protocol_0_in_2_a_bits_data     (auto_in_2_a_bits_data),
    .io_protocol_0_in_2_a_bits_corrupt  (auto_in_2_a_bits_corrupt),
    .io_protocol_0_in_2_b_ready         (auto_in_2_b_ready),
    .io_protocol_0_in_2_b_valid         (auto_in_2_b_valid),
    .io_protocol_0_in_2_b_bits_opcode   (auto_in_2_b_bits_opcode),
    .io_protocol_0_in_2_b_bits_param    (auto_in_2_b_bits_param),
    .io_protocol_0_in_2_b_bits_size     (auto_in_2_b_bits_size),
    .io_protocol_0_in_2_b_bits_source   (auto_in_2_b_bits_source),
    .io_protocol_0_in_2_b_bits_address  (auto_in_2_b_bits_address),
    .io_protocol_0_in_2_b_bits_mask     (auto_in_2_b_bits_mask),
    .io_protocol_0_in_2_b_bits_data     (auto_in_2_b_bits_data),
    .io_protocol_0_in_2_b_bits_corrupt  (auto_in_2_b_bits_corrupt),
    .io_protocol_0_in_2_c_ready         (auto_in_2_c_ready),
    .io_protocol_0_in_2_c_valid         (auto_in_2_c_valid),
    .io_protocol_0_in_2_c_bits_opcode   (auto_in_2_c_bits_opcode),
    .io_protocol_0_in_2_c_bits_param    (auto_in_2_c_bits_param),
    .io_protocol_0_in_2_c_bits_size     (auto_in_2_c_bits_size),
    .io_protocol_0_in_2_c_bits_source   (auto_in_2_c_bits_source),
    .io_protocol_0_in_2_c_bits_address  (auto_in_2_c_bits_address),
    .io_protocol_0_in_2_c_bits_data     (auto_in_2_c_bits_data),
    .io_protocol_0_in_2_c_bits_corrupt  (auto_in_2_c_bits_corrupt),
    .io_protocol_0_in_2_d_ready         (auto_in_2_d_ready),
    .io_protocol_0_in_2_d_valid         (auto_in_2_d_valid),
    .io_protocol_0_in_2_d_bits_opcode   (auto_in_2_d_bits_opcode),
    .io_protocol_0_in_2_d_bits_param    (auto_in_2_d_bits_param),
    .io_protocol_0_in_2_d_bits_size     (auto_in_2_d_bits_size),
    .io_protocol_0_in_2_d_bits_source   (auto_in_2_d_bits_source),
    .io_protocol_0_in_2_d_bits_sink     (auto_in_2_d_bits_sink),
    .io_protocol_0_in_2_d_bits_denied   (auto_in_2_d_bits_denied),
    .io_protocol_0_in_2_d_bits_data     (auto_in_2_d_bits_data),
    .io_protocol_0_in_2_d_bits_corrupt  (auto_in_2_d_bits_corrupt),
    .io_protocol_0_in_2_e_ready         (auto_in_2_e_ready),
    .io_protocol_0_in_2_e_valid         (auto_in_2_e_valid),
    .io_protocol_0_in_2_e_bits_sink     (auto_in_2_e_bits_sink),
    .io_protocol_0_in_1_a_ready         (auto_in_1_a_ready),
    .io_protocol_0_in_1_a_valid         (auto_in_1_a_valid),
    .io_protocol_0_in_1_a_bits_opcode   (auto_in_1_a_bits_opcode),
    .io_protocol_0_in_1_a_bits_param    (auto_in_1_a_bits_param),
    .io_protocol_0_in_1_a_bits_size     (auto_in_1_a_bits_size),
    .io_protocol_0_in_1_a_bits_source   (auto_in_1_a_bits_source),
    .io_protocol_0_in_1_a_bits_address  (auto_in_1_a_bits_address),
    .io_protocol_0_in_1_a_bits_mask     (auto_in_1_a_bits_mask),
    .io_protocol_0_in_1_a_bits_data     (auto_in_1_a_bits_data),
    .io_protocol_0_in_1_a_bits_corrupt  (auto_in_1_a_bits_corrupt),
    .io_protocol_0_in_1_b_ready         (auto_in_1_b_ready),
    .io_protocol_0_in_1_b_valid         (auto_in_1_b_valid),
    .io_protocol_0_in_1_b_bits_opcode   (auto_in_1_b_bits_opcode),
    .io_protocol_0_in_1_b_bits_param    (auto_in_1_b_bits_param),
    .io_protocol_0_in_1_b_bits_size     (auto_in_1_b_bits_size),
    .io_protocol_0_in_1_b_bits_source   (auto_in_1_b_bits_source),
    .io_protocol_0_in_1_b_bits_address  (auto_in_1_b_bits_address),
    .io_protocol_0_in_1_b_bits_mask     (auto_in_1_b_bits_mask),
    .io_protocol_0_in_1_b_bits_data     (auto_in_1_b_bits_data),
    .io_protocol_0_in_1_b_bits_corrupt  (auto_in_1_b_bits_corrupt),
    .io_protocol_0_in_1_c_ready         (auto_in_1_c_ready),
    .io_protocol_0_in_1_c_valid         (auto_in_1_c_valid),
    .io_protocol_0_in_1_c_bits_opcode   (auto_in_1_c_bits_opcode),
    .io_protocol_0_in_1_c_bits_param    (auto_in_1_c_bits_param),
    .io_protocol_0_in_1_c_bits_size     (auto_in_1_c_bits_size),
    .io_protocol_0_in_1_c_bits_source   (auto_in_1_c_bits_source),
    .io_protocol_0_in_1_c_bits_address  (auto_in_1_c_bits_address),
    .io_protocol_0_in_1_c_bits_data     (auto_in_1_c_bits_data),
    .io_protocol_0_in_1_c_bits_corrupt  (auto_in_1_c_bits_corrupt),
    .io_protocol_0_in_1_d_ready         (auto_in_1_d_ready),
    .io_protocol_0_in_1_d_valid         (auto_in_1_d_valid),
    .io_protocol_0_in_1_d_bits_opcode   (auto_in_1_d_bits_opcode),
    .io_protocol_0_in_1_d_bits_param    (auto_in_1_d_bits_param),
    .io_protocol_0_in_1_d_bits_size     (auto_in_1_d_bits_size),
    .io_protocol_0_in_1_d_bits_source   (auto_in_1_d_bits_source),
    .io_protocol_0_in_1_d_bits_sink     (auto_in_1_d_bits_sink),
    .io_protocol_0_in_1_d_bits_denied   (auto_in_1_d_bits_denied),
    .io_protocol_0_in_1_d_bits_data     (auto_in_1_d_bits_data),
    .io_protocol_0_in_1_d_bits_corrupt  (auto_in_1_d_bits_corrupt),
    .io_protocol_0_in_1_e_ready         (auto_in_1_e_ready),
    .io_protocol_0_in_1_e_valid         (auto_in_1_e_valid),
    .io_protocol_0_in_1_e_bits_sink     (auto_in_1_e_bits_sink),
    .io_protocol_0_in_0_a_ready         (auto_in_0_a_ready),
    .io_protocol_0_in_0_a_valid         (auto_in_0_a_valid),
    .io_protocol_0_in_0_a_bits_opcode   (auto_in_0_a_bits_opcode),
    .io_protocol_0_in_0_a_bits_param    (auto_in_0_a_bits_param),
    .io_protocol_0_in_0_a_bits_size     (auto_in_0_a_bits_size),
    .io_protocol_0_in_0_a_bits_source   (auto_in_0_a_bits_source),
    .io_protocol_0_in_0_a_bits_address  (auto_in_0_a_bits_address),
    .io_protocol_0_in_0_a_bits_mask     (auto_in_0_a_bits_mask),
    .io_protocol_0_in_0_a_bits_data     (auto_in_0_a_bits_data),
    .io_protocol_0_in_0_a_bits_corrupt  (auto_in_0_a_bits_corrupt),
    .io_protocol_0_in_0_b_ready         (auto_in_0_b_ready),
    .io_protocol_0_in_0_b_valid         (auto_in_0_b_valid),
    .io_protocol_0_in_0_b_bits_opcode   (auto_in_0_b_bits_opcode),
    .io_protocol_0_in_0_b_bits_param    (auto_in_0_b_bits_param),
    .io_protocol_0_in_0_b_bits_size     (auto_in_0_b_bits_size),
    .io_protocol_0_in_0_b_bits_source   (auto_in_0_b_bits_source),
    .io_protocol_0_in_0_b_bits_address  (auto_in_0_b_bits_address),
    .io_protocol_0_in_0_b_bits_mask     (auto_in_0_b_bits_mask),
    .io_protocol_0_in_0_b_bits_data     (auto_in_0_b_bits_data),
    .io_protocol_0_in_0_b_bits_corrupt  (auto_in_0_b_bits_corrupt),
    .io_protocol_0_in_0_c_ready         (auto_in_0_c_ready),
    .io_protocol_0_in_0_c_valid         (auto_in_0_c_valid),
    .io_protocol_0_in_0_c_bits_opcode   (auto_in_0_c_bits_opcode),
    .io_protocol_0_in_0_c_bits_param    (auto_in_0_c_bits_param),
    .io_protocol_0_in_0_c_bits_size     (auto_in_0_c_bits_size),
    .io_protocol_0_in_0_c_bits_source   (auto_in_0_c_bits_source),
    .io_protocol_0_in_0_c_bits_address  (auto_in_0_c_bits_address),
    .io_protocol_0_in_0_c_bits_data     (auto_in_0_c_bits_data),
    .io_protocol_0_in_0_c_bits_corrupt  (auto_in_0_c_bits_corrupt),
    .io_protocol_0_in_0_d_ready         (auto_in_0_d_ready),
    .io_protocol_0_in_0_d_valid         (auto_in_0_d_valid),
    .io_protocol_0_in_0_d_bits_opcode   (auto_in_0_d_bits_opcode),
    .io_protocol_0_in_0_d_bits_param    (auto_in_0_d_bits_param),
    .io_protocol_0_in_0_d_bits_size     (auto_in_0_d_bits_size),
    .io_protocol_0_in_0_d_bits_source   (auto_in_0_d_bits_source),
    .io_protocol_0_in_0_d_bits_sink     (auto_in_0_d_bits_sink),
    .io_protocol_0_in_0_d_bits_denied   (auto_in_0_d_bits_denied),
    .io_protocol_0_in_0_d_bits_data     (auto_in_0_d_bits_data),
    .io_protocol_0_in_0_d_bits_corrupt  (auto_in_0_d_bits_corrupt),
    .io_protocol_0_in_0_e_ready         (auto_in_0_e_ready),
    .io_protocol_0_in_0_e_valid         (auto_in_0_e_valid),
    .io_protocol_0_in_0_e_bits_sink     (auto_in_0_e_bits_sink),
    .io_protocol_0_out_1_a_ready        (auto_out_1_a_ready),
    .io_protocol_0_out_1_a_valid        (auto_out_1_a_valid),
    .io_protocol_0_out_1_a_bits_opcode  (auto_out_1_a_bits_opcode),
    .io_protocol_0_out_1_a_bits_param   (auto_out_1_a_bits_param),
    .io_protocol_0_out_1_a_bits_size    (auto_out_1_a_bits_size),
    .io_protocol_0_out_1_a_bits_source  (auto_out_1_a_bits_source),
    .io_protocol_0_out_1_a_bits_address (auto_out_1_a_bits_address),
    .io_protocol_0_out_1_a_bits_mask    (auto_out_1_a_bits_mask),
    .io_protocol_0_out_1_a_bits_data    (auto_out_1_a_bits_data),
    .io_protocol_0_out_1_b_ready        (auto_out_1_b_ready),
    .io_protocol_0_out_1_b_valid        (auto_out_1_b_valid),
    .io_protocol_0_out_1_b_bits_param   (auto_out_1_b_bits_param),
    .io_protocol_0_out_1_b_bits_source  (auto_out_1_b_bits_source),
    .io_protocol_0_out_1_b_bits_address (auto_out_1_b_bits_address),
    .io_protocol_0_out_1_c_ready        (auto_out_1_c_ready),
    .io_protocol_0_out_1_c_valid        (auto_out_1_c_valid),
    .io_protocol_0_out_1_c_bits_opcode  (auto_out_1_c_bits_opcode),
    .io_protocol_0_out_1_c_bits_param   (auto_out_1_c_bits_param),
    .io_protocol_0_out_1_c_bits_size    (auto_out_1_c_bits_size),
    .io_protocol_0_out_1_c_bits_source  (auto_out_1_c_bits_source),
    .io_protocol_0_out_1_c_bits_address (auto_out_1_c_bits_address),
    .io_protocol_0_out_1_c_bits_data    (auto_out_1_c_bits_data),
    .io_protocol_0_out_1_d_ready        (auto_out_1_d_ready),
    .io_protocol_0_out_1_d_valid        (auto_out_1_d_valid),
    .io_protocol_0_out_1_d_bits_opcode  (auto_out_1_d_bits_opcode),
    .io_protocol_0_out_1_d_bits_param   (auto_out_1_d_bits_param),
    .io_protocol_0_out_1_d_bits_size    (auto_out_1_d_bits_size),
    .io_protocol_0_out_1_d_bits_source  (auto_out_1_d_bits_source),
    .io_protocol_0_out_1_d_bits_sink    (auto_out_1_d_bits_sink),
    .io_protocol_0_out_1_d_bits_denied  (auto_out_1_d_bits_denied),
    .io_protocol_0_out_1_d_bits_data    (auto_out_1_d_bits_data),
    .io_protocol_0_out_1_d_bits_corrupt (auto_out_1_d_bits_corrupt),
    .io_protocol_0_out_1_e_valid        (auto_out_1_e_valid),
    .io_protocol_0_out_1_e_bits_sink    (auto_out_1_e_bits_sink),
    .io_protocol_0_out_0_a_ready        (auto_out_0_a_ready),
    .io_protocol_0_out_0_a_valid        (auto_out_0_a_valid),
    .io_protocol_0_out_0_a_bits_opcode  (auto_out_0_a_bits_opcode),
    .io_protocol_0_out_0_a_bits_param   (auto_out_0_a_bits_param),
    .io_protocol_0_out_0_a_bits_size    (auto_out_0_a_bits_size),
    .io_protocol_0_out_0_a_bits_source  (auto_out_0_a_bits_source),
    .io_protocol_0_out_0_a_bits_address (auto_out_0_a_bits_address),
    .io_protocol_0_out_0_a_bits_mask    (auto_out_0_a_bits_mask),
    .io_protocol_0_out_0_a_bits_data    (auto_out_0_a_bits_data),
    .io_protocol_0_out_0_a_bits_corrupt (auto_out_0_a_bits_corrupt),
    .io_protocol_0_out_0_d_ready        (auto_out_0_d_ready),
    .io_protocol_0_out_0_d_valid        (auto_out_0_d_valid),
    .io_protocol_0_out_0_d_bits_opcode  (auto_out_0_d_bits_opcode),
    .io_protocol_0_out_0_d_bits_param   (auto_out_0_d_bits_param),
    .io_protocol_0_out_0_d_bits_size    (auto_out_0_d_bits_size),
    .io_protocol_0_out_0_d_bits_source  (auto_out_0_d_bits_source),
    .io_protocol_0_out_0_d_bits_sink    (auto_out_0_d_bits_sink),
    .io_protocol_0_out_0_d_bits_denied  (auto_out_0_d_bits_denied),
    .io_protocol_0_out_0_d_bits_data    (auto_out_0_d_bits_data),
    .io_protocol_0_out_0_d_bits_corrupt (auto_out_0_d_bits_corrupt)
  );	// @[generators/constellation/src/main/scala/protocol/Tilelink.scala:561:21]
endmodule

