// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TRNGMMIOModule(	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
  input         clock,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
  input         reset,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
  input         io_iRst,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  input         io_iEn,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  input  [31:0] io_iDelay,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  input         io_iNext,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  output        io_oValid,	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
  output [31:0] io_oRand	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
);

  wire [4:0]  _ro_io_o_out;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
  wire        _rg_io_o_bit;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20]
  reg         tick;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23]
  reg  [31:0] delayCnt;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27]
  reg  [31:0] shiftReg;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:93:27]
  reg  [4:0]  collectCnt;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29]
  reg         valid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:95:24]
  reg         nextTrigger_REG;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:98:44]
  wire        _GEN = io_iEn & ~tick;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23, :80:{17,20}]
  wire        _GEN_0 = io_iRst | io_iNext & ~nextTrigger_REG;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:98:{33,36,44}, :101:18]
  wire        _GEN_1 = tick & ~valid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23, :95:24, :106:{15,18}]
  always @(posedge clock) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    if (reset) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      tick <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23]
      delayCnt <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27]
      shiftReg <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:93:27]
      collectCnt <= 5'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29]
      valid <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:95:24]
    end
    else begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      tick <= ~io_iRst & (_GEN & delayCnt == io_iDelay | tick);	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:73:23, :74:27, :76:18, :78:10, :80:{17,27}, :82:{23,38}, :83:14, :85:14, :89:14]
      if (io_iRst)	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:44:16]
        delayCnt <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27]
      else if (_GEN)	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:80:17]
        delayCnt <= delayCnt + 32'h1;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:74:27, :81:30]
      if (_GEN_0) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:101:18]
        shiftReg <= 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:93:27]
        collectCnt <= 5'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29]
      end
      else if (_GEN_1) begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:106:15]
        shiftReg <= {shiftReg[30:0], _rg_io_o_bit};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20, :93:27, :107:{30,38}]
        collectCnt <= collectCnt + 5'h1;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29, :108:34]
      end
      valid <= ~_GEN_0 & (_GEN_1 & (&collectCnt) | valid);	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:94:29, :95:24, :101:{18,33}, :103:11, :106:{15,26}, :109:{25,35}, :110:15, :112:15]
    end
    nextTrigger_REG <= io_iNext;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:98:44]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    initial begin	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        end	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
        tick = _RANDOM[2'h0][0];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :73:23]
        delayCnt = {_RANDOM[2'h0][31:1], _RANDOM[2'h1][0]};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :73:23, :74:27]
        shiftReg = {_RANDOM[2'h1][31:1], _RANDOM[2'h2][0]};	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :74:27, :93:27]
        collectCnt = _RANDOM[2'h2][5:1];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :94:29]
        valid = _RANDOM[2'h2][6];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :95:24]
        nextTrigger_REG = _RANDOM[2'h2][8];	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :98:44]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RingGenerator rg (	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20]
    .clock       (clock),
    .reset       (reset),
    .io_i_rst    (io_iRst),
    .io_i_inject (_ro_io_o_out),	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
    .io_o_bit    (_rg_io_o_bit)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:51:20]
  RingOscillator ro (	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
    .io_i_en  (io_iEn),
    .io_o_out (_ro_io_o_out)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:52:20]
  assign io_oValid = valid;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :95:24]
  assign io_oRand = valid ? shiftReg : 32'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/trng.scala:41:7, :93:27, :95:24, :119:20]
endmodule


// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RingGenerator(	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
  input        clock,	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
  input        reset,	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
  input        io_i_rst,	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:20:14]
  input  [4:0] io_i_inject,	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:20:14]
  output       io_o_bit	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:20:14]
);

  reg stateReg_0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_1;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_2;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_3;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_4;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_5;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_6;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_7;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_8;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_9;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_10;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_11;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_12;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_13;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_14;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_15;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_16;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_17;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_18;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_19;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_20;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_21;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_22;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_23;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_24;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_25;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_26;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_27;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_28;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_29;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_30;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  reg stateReg_31;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28]
  always @(posedge clock) begin	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
    if (reset) begin	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
      stateReg_0 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_1 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_2 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_3 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_4 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_5 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_6 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_7 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_8 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_9 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_10 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_11 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_12 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_13 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_14 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_15 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_16 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_17 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_18 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_19 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_20 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_21 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_22 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_23 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_24 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_25 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_26 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_27 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_28 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_29 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_30 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      stateReg_31 <= 1'h0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
    end
    else begin	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
      stateReg_0 <= ~io_i_rst & stateReg_31;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :61:17]
      stateReg_1 <= ~io_i_rst & stateReg_0;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17]
      stateReg_2 <= ~io_i_rst & stateReg_1;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_3 <= ~io_i_rst & (stateReg_2 ^ stateReg_29);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :67:{25,40}]
      stateReg_4 <= ~io_i_rst & stateReg_3;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_5 <= ~io_i_rst & stateReg_4;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_6 <= ~io_i_rst & (stateReg_5 ^ stateReg_26);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :67:{25,40}]
      stateReg_7 <= ~io_i_rst & stateReg_6;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_8 <= ~io_i_rst & (stateReg_7 ^ stateReg_23);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :67:{25,40}]
      stateReg_9 <= ~io_i_rst & stateReg_8;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_10 <= ~io_i_rst & stateReg_9;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_11 <= ~io_i_rst & (stateReg_10 ^ stateReg_20);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :67:{25,40}]
      stateReg_12 <= ~io_i_rst & stateReg_11;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_13 <= ~io_i_rst & stateReg_12;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_14 <= ~io_i_rst & (stateReg_13 ^ stateReg_18);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :67:{25,40}]
      stateReg_15 <= ~io_i_rst & stateReg_14;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_16 <= ~io_i_rst & stateReg_15;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_17 <= ~io_i_rst & (stateReg_16 ^ io_i_inject[0]);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :64:{25,40,53}]
      stateReg_18 <= ~io_i_rst & stateReg_17;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_19 <= ~io_i_rst & stateReg_18;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_20 <= ~io_i_rst & (stateReg_19 ^ io_i_inject[1]);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :64:{25,40,53}]
      stateReg_21 <= ~io_i_rst & stateReg_20;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_22 <= ~io_i_rst & stateReg_21;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_23 <= ~io_i_rst & (stateReg_22 ^ io_i_inject[2]);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :64:{25,40,53}]
      stateReg_24 <= ~io_i_rst & stateReg_23;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_25 <= ~io_i_rst & stateReg_24;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_26 <= ~io_i_rst & (stateReg_25 ^ io_i_inject[3]);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :64:{25,40,53}]
      stateReg_27 <= ~io_i_rst & stateReg_26;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_28 <= ~io_i_rst & stateReg_27;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_29 <= ~io_i_rst & (stateReg_28 ^ io_i_inject[4]);	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :64:{25,40,53}]
      stateReg_30 <= ~io_i_rst & stateReg_29;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
      stateReg_31 <= ~io_i_rst & stateReg_30;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:27:28, :55:17, :57:19, :60:17, :70:25]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
    initial begin	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
        stateReg_0 = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_2 = _RANDOM[/*Zero width*/ 1'b0][2];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_3 = _RANDOM[/*Zero width*/ 1'b0][3];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_4 = _RANDOM[/*Zero width*/ 1'b0][4];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_5 = _RANDOM[/*Zero width*/ 1'b0][5];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_6 = _RANDOM[/*Zero width*/ 1'b0][6];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_7 = _RANDOM[/*Zero width*/ 1'b0][7];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_8 = _RANDOM[/*Zero width*/ 1'b0][8];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_9 = _RANDOM[/*Zero width*/ 1'b0][9];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_10 = _RANDOM[/*Zero width*/ 1'b0][10];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_11 = _RANDOM[/*Zero width*/ 1'b0][11];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_12 = _RANDOM[/*Zero width*/ 1'b0][12];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_13 = _RANDOM[/*Zero width*/ 1'b0][13];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_14 = _RANDOM[/*Zero width*/ 1'b0][14];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_15 = _RANDOM[/*Zero width*/ 1'b0][15];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_16 = _RANDOM[/*Zero width*/ 1'b0][16];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_17 = _RANDOM[/*Zero width*/ 1'b0][17];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_18 = _RANDOM[/*Zero width*/ 1'b0][18];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_19 = _RANDOM[/*Zero width*/ 1'b0][19];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_20 = _RANDOM[/*Zero width*/ 1'b0][20];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_21 = _RANDOM[/*Zero width*/ 1'b0][21];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_22 = _RANDOM[/*Zero width*/ 1'b0][22];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_23 = _RANDOM[/*Zero width*/ 1'b0][23];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_24 = _RANDOM[/*Zero width*/ 1'b0][24];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_25 = _RANDOM[/*Zero width*/ 1'b0][25];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_26 = _RANDOM[/*Zero width*/ 1'b0][26];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_27 = _RANDOM[/*Zero width*/ 1'b0][27];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_28 = _RANDOM[/*Zero width*/ 1'b0][28];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_29 = _RANDOM[/*Zero width*/ 1'b0][29];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_30 = _RANDOM[/*Zero width*/ 1'b0][30];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
        stateReg_31 = _RANDOM[/*Zero width*/ 1'b0][31];	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_o_bit = stateReg_31;	// @[generators/chipyard/src/main/scala/cipher/trng/base.scala:19:7, :27:28]
endmodule


// Generated by CIRCT firtool-1.75.0
module RingOscillator(	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:39:7]
  input        io_i_en,	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:40:14]
  output [4:0] io_o_out	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:40:14]
);

  wire _asic_nand_0_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
  wire _inv_modules_asic_not_3_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  wire _inv_modules_asic_not_2_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  wire _inv_modules_asic_not_1_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  wire _inv_modules_asic_not_0_y;	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_0 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_asic_nand_0_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
    .y (_inv_modules_asic_not_0_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_1 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_inv_modules_asic_not_0_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_inv_modules_asic_not_1_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_2 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_inv_modules_asic_not_1_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_inv_modules_asic_not_2_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_not inv_modules_asic_not_3 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .a (_inv_modules_asic_not_2_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_inv_modules_asic_not_3_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
  asic_nand asic_nand_0 (	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
    .a (io_i_en),
    .b (_inv_modules_asic_not_3_y),	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:85:21]
    .y (_asic_nand_0_y)
  );	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:90:29]
  assign io_o_out = {_inv_modules_asic_not_3_y, _inv_modules_asic_not_2_y, _inv_modules_asic_not_1_y, _inv_modules_asic_not_0_y, _asic_nand_0_y};	// @[generators/chipyard/src/main/scala/cipher/trng/ro.scala:39:7, :85:21, :90:29, :112:19]
endmodule


module asic_not(input wire a, output wire y);
  assign y = ~a;
endmodule


module asic_nand(input wire a, input wire b, output wire y);
  assign y = ~(a & b);
endmodule